INSERT INTO "public"."relationship_options" (name) VALUES ('Managed you directly');
INSERT INTO "public"."relationship_options" (name) VALUES ('Reported directly to you');
INSERT INTO "public"."relationship_options" (name) VALUES ('Was senior to you but didn''t manage directly');
INSERT INTO "public"."relationship_options" (name) VALUES ('You were senior but didn''t manage directly');
INSERT INTO "public"."relationship_options" (name) VALUES ('Worked with you in the same group');
INSERT INTO "public"."relationship_options" (name) VALUES ('Worked with you in a different group');
INSERT INTO "public"."relationship_options" (name) VALUES ('Worked with you but at different companies');
INSERT INTO "public"."relationship_options" (name) VALUES ('Was a client of yours');
INSERT INTO "public"."relationship_options" (name) VALUES ('You were a client of theirs');
INSERT INTO "public"."relationship_options" (name) VALUES ('Taught you');
INSERT INTO "public"."relationship_options" (name) VALUES ('Mentored you');
INSERT INTO "public"."relationship_options" (name) VALUES ('You were students together');
INSERT INTO "public"."relationship_options" (name) VALUES ('Worked with you on a project');
INSERT INTO "public"."relationship_options" (name) VALUES ('Was in a supervisory committee');
INSERT INTO "public"."relationship_options" (name) VALUES ('Was a supplier or dealer');
INSERT INTO "public"."relationship_options" (name) VALUES ('Provided professional services');
INSERT INTO "public"."relationship_options" (name) VALUES ('Was a coworker but in different departments');
INSERT INTO "public"."relationship_options" (name) VALUES ('Was in the same professional network');
INSERT INTO "public"."relationship_options" (name) VALUES ('Worked with you as a partner or associate');
INSERT INTO "public"."relationship_options" (name) VALUES ('Was a research collaborator');
INSERT INTO "public"."relationship_options" (name) VALUES ('Provided training or guidance');
INSERT INTO "public"."relationship_options" (name) VALUES ('Received training or guidance from you');
INSERT INTO "public"."relationship_options" (name) VALUES ('Shared the same mentor');
INSERT INTO "public"."relationship_options" (name) VALUES ('You were their intern or trainee');
INSERT INTO "public"."relationship_options" (name) VALUES ('They were your intern or trainee');
INSERT INTO "public"."relationship_options" (name) VALUES ('Worked under your supervision');
INSERT INTO "public"."relationship_options" (name) VALUES ('You worked under their supervision');

INSERT INTO "public"."work_experiences" (name) VALUES ('Product Manager');
INSERT INTO "public"."work_experiences" (name) VALUES ('Software Developer');
INSERT INTO "public"."work_experiences" (name) VALUES ('Data Analyst');
INSERT INTO "public"."work_experiences" (name) VALUES ('UX Designer');
INSERT INTO "public"."work_experiences" (name) VALUES ('DevOps Engineer');
INSERT INTO "public"."work_experiences" (name) VALUES ('SEO Specialist');
INSERT INTO "public"."work_experiences" (name) VALUES ('Cybersecurity Consultant');
INSERT INTO "public"."work_experiences" (name) VALUES ('AI Specialist');
INSERT INTO "public"."work_experiences" (name) VALUES ('Blockchain Developer');
INSERT INTO "public"."work_experiences" (name) VALUES ('Game Developer');
INSERT INTO "public"."work_experiences" (name) VALUES ('Database Administrator');
INSERT INTO "public"."work_experiences" (name) VALUES ('Front-End Developer');
INSERT INTO "public"."work_experiences" (name) VALUES ('Back-End Developer');
INSERT INTO "public"."work_experiences" (name) VALUES ('Full Stack Developer');
INSERT INTO "public"."work_experiences" (name) VALUES ('Quality Assurance Specialist');
INSERT INTO "public"."work_experiences" (name) VALUES ('IT Project Manager');
INSERT INTO "public"."work_experiences" (name) VALUES ('Network Architect');
INSERT INTO "public"."work_experiences" (name) VALUES ('Mobile App Developer');
INSERT INTO "public"."work_experiences" (name) VALUES ('System Administrator');
INSERT INTO "public"."work_experiences" (name) VALUES ('Business Intelligence Analyst');
INSERT INTO "public"."work_experiences" (name) VALUES ('Graphic Designer');
INSERT INTO "public"."work_experiences" (name) VALUES ('Content Writer');
INSERT INTO "public"."work_experiences" (name) VALUES ('Marketing Strategist');
INSERT INTO "public"."work_experiences" (name) VALUES ('Customer Support Specialist');
INSERT INTO "public"."work_experiences" (name) VALUES ('E-commerce Specialist');
