INSERT INTO "public"."skills" (name) VALUES ('Python');
INSERT INTO "public"."skills" (name) VALUES ('JavaScript');
INSERT INTO "public"."skills" (name) VALUES ('Java');
INSERT INTO "public"."skills" (name) VALUES ('C++');
INSERT INTO "public"."skills" (name) VALUES ('C#');
INSERT INTO "public"."skills" (name) VALUES ('Ruby');
INSERT INTO "public"."skills" (name) VALUES ('Swift');
INSERT INTO "public"."skills" (name) VALUES ('Kotlin');
INSERT INTO "public"."skills" (name) VALUES ('Scala');
INSERT INTO "public"."skills" (name) VALUES ('PHP');
INSERT INTO "public"."skills" (name) VALUES ('Rust');
INSERT INTO "public"."skills" (name) VALUES ('Go');
INSERT INTO "public"."skills" (name) VALUES ('TypeScript');
INSERT INTO "public"."skills" (name) VALUES ('Shell Scripting');
INSERT INTO "public"."skills" (name) VALUES ('SQL');
INSERT INTO "public"."skills" (name) VALUES ('NoSQL');
INSERT INTO "public"."skills" (name) VALUES ('MongoDB');
INSERT INTO "public"."skills" (name) VALUES ('PostgreSQL');
INSERT INTO "public"."skills" (name) VALUES ('Firebase');
INSERT INTO "public"."skills" (name) VALUES ('Docker');
INSERT INTO "public"."skills" (name) VALUES ('Kubernetes');
INSERT INTO "public"."skills" (name) VALUES ('Ansible');
INSERT INTO "public"."skills" (name) VALUES ('Ethereum Smart Contracts');
INSERT INTO "public"."skills" (name) VALUES ('Solidity');
INSERT INTO "public"."skills" (name) VALUES ('Web3.js');
INSERT INTO "public"."skills" (name) VALUES ('Truffle Framework');
INSERT INTO "public"."skills" (name) VALUES ('Hyperledger Fabric');
INSERT INTO "public"."skills" (name) VALUES ('Corda');
INSERT INTO "public"."skills" (name) VALUES ('IPFS');
INSERT INTO "public"."skills" (name) VALUES ('DApps');
INSERT INTO "public"."skills" (name) VALUES ('Chaincode');
INSERT INTO "public"."skills" (name) VALUES ('Crypto Tokens');
INSERT INTO "public"."skills" (name) VALUES ('Polkadot');
INSERT INTO "public"."skills" (name) VALUES ('Layer 2 Solutions');
INSERT INTO "public"."skills" (name) VALUES ('DeFi');
INSERT INTO "public"."skills" (name) VALUES ('NFTs');
INSERT INTO "public"."skills" (name) VALUES ('Blockchain Interoperability');
INSERT INTO "public"."skills" (name) VALUES ('Smart Contract Audit');
INSERT INTO "public"."skills" (name) VALUES ('Substrate');
INSERT INTO "public"."skills" (name) VALUES ('Cosmos');
INSERT INTO "public"."skills" (name) VALUES ('Cardano');
INSERT INTO "public"."skills" (name) VALUES ('Binance Smart Chain');
INSERT INTO "public"."skills" (name) VALUES ('Zk-SNARKs');
INSERT INTO "public"."skills" (name) VALUES ('Stellar');
INSERT INTO "public"."skills" (name) VALUES ('Tezos');
INSERT INTO "public"."skills" (name) VALUES ('DAG');
INSERT INTO "public"."skills" (name) VALUES ('Hashgraph');
INSERT INTO "public"."skills" (name) VALUES ('Filecoin');
INSERT INTO "public"."skills" (name) VALUES ('DAOs');
INSERT INTO "public"."skills" (name) VALUES ('Ripple');
INSERT INTO "public"."skills" (name) VALUES ('Neo');
INSERT INTO "public"."skills" (name) VALUES ('EOS');
INSERT INTO "public"."skills" (name) VALUES ('Vyper');
INSERT INTO "public"."skills" (name) VALUES ('Quorum');
INSERT INTO "public"."skills" (name) VALUES ('Holochain');
INSERT INTO "public"."skills" (name) VALUES ('Agile Project Management');
INSERT INTO "public"."skills" (name) VALUES ('Quality Assurance');
INSERT INTO "public"."skills" (name) VALUES ('Scrum');
INSERT INTO "public"."skills" (name) VALUES ('Business Analysis');
INSERT INTO "public"."skills" (name) VALUES ('Data Visualization');
INSERT INTO "public"."skills" (name) VALUES ('Big Data');
INSERT INTO "public"."skills" (name) VALUES ('Artificial Intelligence');
INSERT INTO "public"."skills" (name) VALUES ('Machine Learning');
INSERT INTO "public"."skills" (name) VALUES ('DevOps');
INSERT INTO "public"."skills" (name) VALUES ('IT Security');
INSERT INTO "public"."skills" (name) VALUES ('Penetration Testing');
INSERT INTO "public"."skills" (name) VALUES ('Cybersecurity');
INSERT INTO "public"."skills" (name) VALUES ('IT Support');
INSERT INTO "public"."skills" (name) VALUES ('Network Administration');
INSERT INTO "public"."skills" (name) VALUES ('Database Administration');
INSERT INTO "public"."skills" (name) VALUES ('Systems Administration');
INSERT INTO "public"."skills" (name) VALUES ('Cloud Computing');
INSERT INTO "public"."skills" (name) VALUES ('Azure');
INSERT INTO "public"."skills" (name) VALUES ('AWS');
INSERT INTO "public"."skills" (name) VALUES ('GCP');
INSERT INTO "public"."skills" (name) VALUES ('Virtualization');
INSERT INTO "public"."skills" (name) VALUES ('Hardware Troubleshooting');
INSERT INTO "public"."skills" (name) VALUES ('Software Troubleshooting');
INSERT INTO "public"."skills" (name) VALUES ('IT Consulting');
INSERT INTO "public"."skills" (name) VALUES ('IT Strategy');
INSERT INTO "public"."skills" (name) VALUES ('Digital Transformation');
INSERT INTO "public"."skills" (name) VALUES ('UI/UX Design');
INSERT INTO "public"."skills" (name) VALUES ('Interaction Design');
INSERT INTO "public"."skills" (name) VALUES ('Wireframing');
INSERT INTO "public"."skills" (name) VALUES ('Prototyping');
INSERT INTO "public"."skills" (name) VALUES ('Information Architecture');
INSERT INTO "public"."skills" (name) VALUES ('Front-end Development');
INSERT INTO "public"."skills" (name) VALUES ('Back-end Development');
INSERT INTO "public"."skills" (name) VALUES ('Full Stack Development');
INSERT INTO "public"."skills" (name) VALUES ('Mobile App Development');
INSERT INTO "public"."skills" (name) VALUES ('iOS Development');
INSERT INTO "public"."skills" (name) VALUES ('Android Development');
INSERT INTO "public"."skills" (name) VALUES ('Cross-Platform Development');
INSERT INTO "public"."skills" (name) VALUES ('Embedded Systems');
INSERT INTO "public"."skills" (name) VALUES ('IoT');
INSERT INTO "public"."skills" (name) VALUES ('VR/AR Development');
INSERT INTO "public"."skills" (name) VALUES ('Game Design');
INSERT INTO "public"."skills" (name) VALUES ('Game Programming');
INSERT INTO "public"."skills" (name) VALUES ('3D Modeling');
INSERT INTO "public"."skills" (name) VALUES ('Data Science');
INSERT INTO "public"."skills" (name) VALUES ('Quantitative Analysis');
INSERT INTO "public"."skills" (name) VALUES ('Statistics');
INSERT INTO "public"."skills" (name) VALUES ('Power BI');
INSERT INTO "public"."skills" (name) VALUES ('Tableau');
INSERT INTO "public"."skills" (name) VALUES ('React');
INSERT INTO "public"."skills" (name) VALUES ('Angular');
INSERT INTO "public"."skills" (name) VALUES ('Vue.js');
INSERT INTO "public"."skills" (name) VALUES ('Ember.js');
INSERT INTO "public"."skills" (name) VALUES ('Backbone.js');
INSERT INTO "public"."skills" (name) VALUES ('Svelte');
INSERT INTO "public"."skills" (name) VALUES ('Ionic');
INSERT INTO "public"."skills" (name) VALUES ('Flutter for Web');
INSERT INTO "public"."skills" (name) VALUES ('Gatsby.js');
INSERT INTO "public"."skills" (name) VALUES ('Next.js');
INSERT INTO "public"."skills" (name) VALUES ('Nuxt.js');
INSERT INTO "public"."skills" (name) VALUES ('Aurelia');
INSERT INTO "public"."skills" (name) VALUES ('Stimulus');
INSERT INTO "public"."skills" (name) VALUES ('Meteor');
INSERT INTO "public"."skills" (name) VALUES ('Polymer');
INSERT INTO "public"."skills" (name) VALUES ('jQuery');
INSERT INTO "public"."skills" (name) VALUES ('Bootstrap');
INSERT INTO "public"."skills" (name) VALUES ('Material-UI');
INSERT INTO "public"."skills" (name) VALUES ('Tailwind CSS');
INSERT INTO "public"."skills" (name) VALUES ('Sass');
INSERT INTO "public"."skills" (name) VALUES ('Less');
INSERT INTO "public"."skills" (name) VALUES ('Stylus');
INSERT INTO "public"."skills" (name) VALUES ('CSS Modules');
INSERT INTO "public"."skills" (name) VALUES ('PostCSS');
INSERT INTO "public"."skills" (name) VALUES ('BEM');
INSERT INTO "public"."skills" (name) VALUES ('CSS-in-JS');
INSERT INTO "public"."skills" (name) VALUES ('HTML5');
INSERT INTO "public"."skills" (name) VALUES ('CSS3');
INSERT INTO "public"."skills" (name) VALUES ('Web Components');
INSERT INTO "public"."skills" (name) VALUES ('PWA (Progressive Web Apps)');
INSERT INTO "public"."skills" (name) VALUES ('Responsive Web Design');
INSERT INTO "public"."skills" (name) VALUES ('Browser Extension Development');
INSERT INTO "public"."skills" (name) VALUES ('Web Accessibility');
INSERT INTO "public"."skills" (name) VALUES ('SVG Animation');
INSERT INTO "public"."skills" (name) VALUES ('WebGL');
INSERT INTO "public"."skills" (name) VALUES ('Canvas API');
INSERT INTO "public"."skills" (name) VALUES ('Web APIs');
INSERT INTO "public"."skills" (name) VALUES ('Web Performance Optimization');


INSERT INTO "public"."industries" (name) VALUES ('Information Technology');
INSERT INTO "public"."industries" (name) VALUES ('Software Development');
INSERT INTO "public"."industries" (name) VALUES ('Data Analysis');
INSERT INTO "public"."industries" (name) VALUES ('Marketing');
INSERT INTO "public"."industries" (name) VALUES ('Design & Creative');
INSERT INTO "public"."industries" (name) VALUES ('Blockchain');
INSERT INTO "public"."industries" (name) VALUES ('Consulting');
INSERT INTO "public"."industries" (name) VALUES ('Education');
INSERT INTO "public"."industries" (name) VALUES ('Finance');
INSERT INTO "public"."industries" (name) VALUES ('Healthcare');
INSERT INTO "public"."industries" (name) VALUES ('Real Estate');
INSERT INTO "public"."industries" (name) VALUES ('Retail');
INSERT INTO "public"."industries" (name) VALUES ('Manufacturing');
INSERT INTO "public"."industries" (name) VALUES ('Logistics');
INSERT INTO "public"."industries" (name) VALUES ('Entertainment');
INSERT INTO "public"."industries" (name) VALUES ('Publishing');
INSERT INTO "public"."industries" (name) VALUES ('Legal Services');
INSERT INTO "public"."industries" (name) VALUES ('Non-profit');
INSERT INTO "public"."industries" (name) VALUES ('Travel & Hospitality');
INSERT INTO "public"."industries" (name) VALUES ('Energy & Utilities');
INSERT INTO "public"."industries" (name) VALUES ('Agriculture');
INSERT INTO "public"."industries" (name) VALUES ('Biotechnology');
INSERT INTO "public"."industries" (name) VALUES ('Construction');
INSERT INTO "public"."industries" (name) VALUES ('Telecommunications');
INSERT INTO "public"."industries" (name) VALUES ('Automotive');
INSERT INTO "public"."industries" (name) VALUES ('Gaming');
INSERT INTO "public"."industries" (name) VALUES ('E-commerce');
INSERT INTO "public"."industries" (name) VALUES ('Cybersecurity');
INSERT INTO "public"."industries" (name) VALUES ('Artificial Intelligence');
INSERT INTO "public"."industries" (name) VALUES ('Virtual Reality & AR');
INSERT INTO "public"."industries" (name) VALUES ('Machine Learning');
INSERT INTO "public"."industries" (name) VALUES ('Internet of Things');
INSERT INTO "public"."industries" (name) VALUES ('Environmental Services');
INSERT INTO "public"."industries" (name) VALUES ('Human Resources');
INSERT INTO "public"."industries" (name) VALUES ('Personal Services');
INSERT INTO "public"."industries" (name) VALUES ('Fashion & Beauty');
INSERT INTO "public"."industries" (name) VALUES ('Food & Beverage');
INSERT INTO "public"."industries" (name) VALUES ('Home Services');
