UPDATE "public"."skills" SET "name" = 'Accountant' WHERE "id" = 1;
UPDATE "public"."skills" SET "name" = 'Accounts Assistant' WHERE "id" = 2;
UPDATE "public"."skills" SET "name" = 'Accounts Clerk' WHERE "id" = 3;
UPDATE "public"."skills" SET "name" = 'Accounts Manager' WHERE "id" = 4;
UPDATE "public"."skills" SET "name" = 'Accounts Staff' WHERE "id" = 5;
UPDATE "public"."skills" SET "name" = 'Acoustic Engineer' WHERE "id" = 6;
UPDATE "public"."skills" SET "name" = 'Actor' WHERE "id" = 7;
UPDATE "public"."skills" SET "name" = 'Actress' WHERE "id" = 8;
UPDATE "public"."skills" SET "name" = 'Actuary' WHERE "id" = 9;
UPDATE "public"."skills" SET "name" = 'Acupuncturist' WHERE "id" = 10;
UPDATE "public"."skills" SET "name" = 'Adjustor' WHERE "id" = 11;
UPDATE "public"."skills" SET "name" = 'Administration Assistant' WHERE "id" = 12;
UPDATE "public"."skills" SET "name" = 'Administration Clerk' WHERE "id" = 13;
UPDATE "public"."skills" SET "name" = 'Administration Manager' WHERE "id" = 14;
UPDATE "public"."skills" SET "name" = 'Administration Staff' WHERE "id" = 15;
UPDATE "public"."skills" SET "name" = 'Administrator' WHERE "id" = 16;
UPDATE "public"."skills" SET "name" = 'Advertising Agent' WHERE "id" = 17;
UPDATE "public"."skills" SET "name" = 'Advertising Assistant' WHERE "id" = 18;
UPDATE "public"."skills" SET "name" = 'Advertising Clerk' WHERE "id" = 19;
UPDATE "public"."skills" SET "name" = 'Advertising Contractor' WHERE "id" = 20;
UPDATE "public"."skills" SET "name" = 'Advertising Executive' WHERE "id" = 21;
UPDATE "public"."skills" SET "name" = 'Advertising Manager' WHERE "id" = 22;
UPDATE "public"."skills" SET "name" = 'Advertising Staff' WHERE "id" = 23;
UPDATE "public"."skills" SET "name" = 'Aerial Erector' WHERE "id" = 24;
UPDATE "public"."skills" SET "name" = 'Aerobic Instructor' WHERE "id" = 25;
UPDATE "public"."skills" SET "name" = 'Aeronautical Engineer' WHERE "id" = 26;
UPDATE "public"."skills" SET "name" = 'Agent' WHERE "id" = 27;
UPDATE "public"."skills" SET "name" = 'Air Traffic Controller' WHERE "id" = 28;
UPDATE "public"."skills" SET "name" = 'Aircraft Designer' WHERE "id" = 29;
UPDATE "public"."skills" SET "name" = 'Aircraft Engineer' WHERE "id" = 30;
UPDATE "public"."skills" SET "name" = 'Aircraft Maintenance Engineer' WHERE "id" = 31;
UPDATE "public"."skills" SET "name" = 'Aircraft Surface Finisher' WHERE "id" = 32;
UPDATE "public"."skills" SET "name" = 'Airman' WHERE "id" = 33;
UPDATE "public"."skills" SET "name" = 'Airport Controller' WHERE "id" = 34;
UPDATE "public"."skills" SET "name" = 'Airport Manager' WHERE "id" = 35;
UPDATE "public"."skills" SET "name" = 'Almoner' WHERE "id" = 36;
UPDATE "public"."skills" SET "name" = 'Ambulance Controller' WHERE "id" = 37;
UPDATE "public"."skills" SET "name" = 'Ambulance Crew' WHERE "id" = 38;
UPDATE "public"."skills" SET "name" = 'Ambulance Driver' WHERE "id" = 39;
UPDATE "public"."skills" SET "name" = 'Amusement Arcade Worker' WHERE "id" = 40;
UPDATE "public"."skills" SET "name" = 'Anaesthetist' WHERE "id" = 41;
UPDATE "public"."skills" SET "name" = 'Analyst' WHERE "id" = 42;
UPDATE "public"."skills" SET "name" = 'Analytical Chemist' WHERE "id" = 43;
UPDATE "public"."skills" SET "name" = 'Animal Breeder' WHERE "id" = 44;
UPDATE "public"."skills" SET "name" = 'Anthropologist' WHERE "id" = 45;
UPDATE "public"."skills" SET "name" = 'Antique Dealer' WHERE "id" = 46;
UPDATE "public"."skills" SET "name" = 'Applications Engineer' WHERE "id" = 47;
UPDATE "public"."skills" SET "name" = 'Applications Programmer' WHERE "id" = 48;
UPDATE "public"."skills" SET "name" = 'Arbitrator' WHERE "id" = 49;
UPDATE "public"."skills" SET "name" = 'Arborist' WHERE "id" = 50;
UPDATE "public"."skills" SET "name" = 'Archaeologist' WHERE "id" = 51;
UPDATE "public"."skills" SET "name" = 'Architect' WHERE "id" = 52;
UPDATE "public"."skills" SET "name" = 'Archivist' WHERE "id" = 53;
UPDATE "public"."skills" SET "name" = 'Area Manager' WHERE "id" = 54;
UPDATE "public"."skills" SET "name" = 'Armourer' WHERE "id" = 55;
UPDATE "public"."skills" SET "name" = 'Aromatherapist' WHERE "id" = 56;
UPDATE "public"."skills" SET "name" = 'Art Critic' WHERE "id" = 57;
UPDATE "public"."skills" SET "name" = 'Art Dealer' WHERE "id" = 58;
UPDATE "public"."skills" SET "name" = 'Art Historian' WHERE "id" = 59;
UPDATE "public"."skills" SET "name" = 'Art Restorer' WHERE "id" = 60;
UPDATE "public"."skills" SET "name" = 'Artexer' WHERE "id" = 61;
UPDATE "public"."skills" SET "name" = 'Artist' WHERE "id" = 62;
UPDATE "public"."skills" SET "name" = 'Arts' WHERE "id" = 63;
UPDATE "public"."skills" SET "name" = 'Assembly Worker' WHERE "id" = 64;
UPDATE "public"."skills" SET "name" = 'Assessor' WHERE "id" = 65;
UPDATE "public"."skills" SET "name" = 'Assistant' WHERE "id" = 66;
UPDATE "public"."skills" SET "name" = 'Assistant Caretaker' WHERE "id" = 67;
UPDATE "public"."skills" SET "name" = 'Assistant Cook' WHERE "id" = 68;
UPDATE "public"."skills" SET "name" = 'Assistant Manager' WHERE "id" = 69;
UPDATE "public"."skills" SET "name" = 'Assistant Nurse' WHERE "id" = 70;
UPDATE "public"."skills" SET "name" = 'Assistant Teacher' WHERE "id" = 71;
UPDATE "public"."skills" SET "name" = 'Astrologer' WHERE "id" = 72;
UPDATE "public"."skills" SET "name" = 'Astronomer' WHERE "id" = 73;
UPDATE "public"."skills" SET "name" = 'Attendant' WHERE "id" = 74;
UPDATE "public"."skills" SET "name" = 'Au Pair' WHERE "id" = 75;
UPDATE "public"."skills" SET "name" = 'Auction Worker' WHERE "id" = 76;
UPDATE "public"."skills" SET "name" = 'Auctioneer' WHERE "id" = 77;
UPDATE "public"."skills" SET "name" = 'Audiologist' WHERE "id" = 78;
UPDATE "public"."skills" SET "name" = 'Audit Clerk' WHERE "id" = 79;
UPDATE "public"."skills" SET "name" = 'Audit Manager' WHERE "id" = 80;
UPDATE "public"."skills" SET "name" = 'Auditor' WHERE "id" = 81;
UPDATE "public"."skills" SET "name" = 'Auto Electrician' WHERE "id" = 82;
UPDATE "public"."skills" SET "name" = 'Auxiliary Nurse' WHERE "id" = 83;
UPDATE "public"."skills" SET "name" = 'Bacon Curer' WHERE "id" = 84;
UPDATE "public"."skills" SET "name" = 'Baggage Handler' WHERE "id" = 85;
UPDATE "public"."skills" SET "name" = 'Bailiff' WHERE "id" = 86;
UPDATE "public"."skills" SET "name" = 'Baker' WHERE "id" = 87;
UPDATE "public"."skills" SET "name" = 'Bakery Assistant' WHERE "id" = 88;
UPDATE "public"."skills" SET "name" = 'Bakery Manager' WHERE "id" = 89;
UPDATE "public"."skills" SET "name" = 'Bakery Operator' WHERE "id" = 90;
UPDATE "public"."skills" SET "name" = 'Balloonist' WHERE "id" = 91;
UPDATE "public"."skills" SET "name" = 'Bank Clerk' WHERE "id" = 92;
UPDATE "public"."skills" SET "name" = 'Bank Manager' WHERE "id" = 93;
UPDATE "public"."skills" SET "name" = 'Bank Messenger' WHERE "id" = 94;
UPDATE "public"."skills" SET "name" = 'Baptist Minister' WHERE "id" = 95;
UPDATE "public"."skills" SET "name" = 'Bar Manager' WHERE "id" = 96;
UPDATE "public"."skills" SET "name" = 'Bar Steward' WHERE "id" = 97;
UPDATE "public"."skills" SET "name" = 'Barber' WHERE "id" = 98;
UPDATE "public"."skills" SET "name" = 'Barmaid' WHERE "id" = 99;
UPDATE "public"."skills" SET "name" = 'Barman' WHERE "id" = 100;
UPDATE "public"."skills" SET "name" = 'Barrister' WHERE "id" = 101;
UPDATE "public"."skills" SET "name" = 'Beautician' WHERE "id" = 102;
UPDATE "public"."skills" SET "name" = 'Beauty Therapist' WHERE "id" = 103;
UPDATE "public"."skills" SET "name" = 'Betting Shop' WHERE "id" = 104;
UPDATE "public"."skills" SET "name" = 'Bill Poster' WHERE "id" = 105;
UPDATE "public"."skills" SET "name" = 'Bingo Caller' WHERE "id" = 106;
UPDATE "public"."skills" SET "name" = 'Biochemist' WHERE "id" = 107;
UPDATE "public"."skills" SET "name" = 'Biologist' WHERE "id" = 108;
UPDATE "public"."skills" SET "name" = 'Blacksmith' WHERE "id" = 109;
UPDATE "public"."skills" SET "name" = 'Blind Assembler' WHERE "id" = 110;
UPDATE "public"."skills" SET "name" = 'Blind Fitter' WHERE "id" = 111;
UPDATE "public"."skills" SET "name" = 'Blinds Installer' WHERE "id" = 112;
UPDATE "public"."skills" SET "name" = 'Boat Builder' WHERE "id" = 113;
UPDATE "public"."skills" SET "name" = 'Body Fitter' WHERE "id" = 114;
UPDATE "public"."skills" SET "name" = 'Bodyguard' WHERE "id" = 115;
UPDATE "public"."skills" SET "name" = 'Bodyshop' WHERE "id" = 116;
UPDATE "public"."skills" SET "name" = 'Book Binder' WHERE "id" = 117;
UPDATE "public"."skills" SET "name" = 'Book Seller' WHERE "id" = 118;
UPDATE "public"."skills" SET "name" = 'Book-Keeper' WHERE "id" = 119;
UPDATE "public"."skills" SET "name" = 'Booking Agent' WHERE "id" = 120;
UPDATE "public"."skills" SET "name" = 'Booking Clerk' WHERE "id" = 121;
UPDATE "public"."skills" SET "name" = 'Bookmaker' WHERE "id" = 122;
UPDATE "public"."skills" SET "name" = 'Botanist' WHERE "id" = 123;
UPDATE "public"."skills" SET "name" = 'Branch Manager' WHERE "id" = 124;
UPDATE "public"."skills" SET "name" = 'Breeder' WHERE "id" = 125;
UPDATE "public"."skills" SET "name" = 'Brewer' WHERE "id" = 126;
UPDATE "public"."skills" SET "name" = 'Brewery Manager' WHERE "id" = 127;
UPDATE "public"."skills" SET "name" = 'Brewery Worker' WHERE "id" = 128;
UPDATE "public"."skills" SET "name" = 'Bricklayer' WHERE "id" = 129;
UPDATE "public"."skills" SET "name" = 'Broadcaster' WHERE "id" = 130;
UPDATE "public"."skills" SET "name" = 'Builder' WHERE "id" = 131;
UPDATE "public"."skills" SET "name" = 'Builders Labourer' WHERE "id" = 132;
UPDATE "public"."skills" SET "name" = 'Building Advisor' WHERE "id" = 133;
UPDATE "public"."skills" SET "name" = 'Building Control' WHERE "id" = 134;
UPDATE "public"."skills" SET "name" = 'Building Engineer' WHERE "id" = 135;
UPDATE "public"."skills" SET "name" = 'Building Estimator' WHERE "id" = 136;
UPDATE "public"."skills" SET "name" = 'Building Foreman' WHERE "id" = 137;
UPDATE "public"."skills" SET "name" = 'Building Inspector' WHERE "id" = 138;
UPDATE "public"."skills" SET "name" = 'Building Manager' WHERE "id" = 139;
UPDATE "public"."skills" SET "name" = 'Building Surveyor' WHERE "id" = 140;
UPDATE "public"."skills" SET "name" = 'Bursar' WHERE "id" = 141;
UPDATE "public"."skills" SET "name" = 'Bus Company' WHERE "id" = 142;
UPDATE "public"."skills" SET "name" = 'Bus Conductor' WHERE "id" = 143;
UPDATE "public"."skills" SET "name" = 'Bus Driver' WHERE "id" = 144;
UPDATE "public"."skills" SET "name" = 'Bus Mechanic' WHERE "id" = 145;
UPDATE "public"."skills" SET "name" = 'Bus Valeter' WHERE "id" = 146;
UPDATE "public"."skills" SET "name" = 'Business Consultant' WHERE "id" = 147;
UPDATE "public"."skills" SET "name" = 'Business Proprietor' WHERE "id" = 148;
UPDATE "public"."skills" SET "name" = 'Butcher' WHERE "id" = 149;
UPDATE "public"."skills" SET "name" = 'Butchery Manager' WHERE "id" = 150;
UPDATE "public"."skills" SET "name" = 'Butler' WHERE "id" = 151;
UPDATE "public"."skills" SET "name" = 'Buyer' WHERE "id" = 152;
UPDATE "public"."skills" SET "name" = 'Cab Driver' WHERE "id" = 153;
UPDATE "public"."skills" SET "name" = 'Cabinet Maker' WHERE "id" = 154;
UPDATE "public"."skills" SET "name" = 'Cable Contractor' WHERE "id" = 155;
UPDATE "public"."skills" SET "name" = 'Cable Jointer' WHERE "id" = 156;
UPDATE "public"."skills" SET "name" = 'Cable TV Installer' WHERE "id" = 157;
UPDATE "public"."skills" SET "name" = 'Cafe Owner' WHERE "id" = 158;
UPDATE "public"."skills" SET "name" = 'Cafe Staff' WHERE "id" = 159;
UPDATE "public"."skills" SET "name" = 'Cafe Worker' WHERE "id" = 160;
UPDATE "public"."skills" SET "name" = 'Calibration Manager' WHERE "id" = 161;
UPDATE "public"."skills" SET "name" = 'Camera Repairer' WHERE "id" = 162;
UPDATE "public"."skills" SET "name" = 'Cameraman' WHERE "id" = 163;
UPDATE "public"."skills" SET "name" = 'Car Dealer' WHERE "id" = 164;
UPDATE "public"."skills" SET "name" = 'Car Delivery Driver' WHERE "id" = 165;
UPDATE "public"."skills" SET "name" = 'Car Park Attendant' WHERE "id" = 166;
UPDATE "public"."skills" SET "name" = 'Car Salesman' WHERE "id" = 167;
UPDATE "public"."skills" SET "name" = 'Car Valet' WHERE "id" = 168;
UPDATE "public"."skills" SET "name" = 'Car Wash Attendant' WHERE "id" = 169;
UPDATE "public"."skills" SET "name" = 'Care Assistant' WHERE "id" = 170;
UPDATE "public"."skills" SET "name" = 'Care Manager' WHERE "id" = 171;
UPDATE "public"."skills" SET "name" = 'Careers Advisor' WHERE "id" = 172;
UPDATE "public"."skills" SET "name" = 'Careers Officer' WHERE "id" = 173;
UPDATE "public"."skills" SET "name" = 'Caretaker' WHERE "id" = 174;
UPDATE "public"."skills" SET "name" = 'Cargo Operator' WHERE "id" = 175;
UPDATE "public"."skills" SET "name" = 'Carpenter' WHERE "id" = 176;
UPDATE "public"."skills" SET "name" = 'Carpet Cleaner' WHERE "id" = 177;
UPDATE "public"."skills" SET "name" = 'Carpet Fitter' WHERE "id" = 178;
UPDATE "public"."skills" SET "name" = 'Carpet Retailer' WHERE "id" = 179;
UPDATE "public"."skills" SET "name" = 'Carphone Fitter' WHERE "id" = 180;
UPDATE "public"."skills" SET "name" = 'Cartographer' WHERE "id" = 181;
UPDATE "public"."skills" SET "name" = 'Cartoonist' WHERE "id" = 182;
UPDATE "public"."skills" SET "name" = 'Cashier' WHERE "id" = 183;
UPDATE "public"."skills" SET "name" = 'Casual Worker' WHERE "id" = 184;
UPDATE "public"."skills" SET "name" = 'Caterer' WHERE "id" = 185;
UPDATE "public"."skills" SET "name" = 'Catering Consultant' WHERE "id" = 186;
UPDATE "public"."skills" SET "name" = 'Catering Manager' WHERE "id" = 187;
UPDATE "public"."skills" SET "name" = 'Catering Staff' WHERE "id" = 188;
UPDATE "public"."skills" SET "name" = 'Caulker' WHERE "id" = 189;
UPDATE "public"."skills" SET "name" = 'Ceiling Contractor' WHERE "id" = 190;
UPDATE "public"."skills" SET "name" = 'Ceiling Fixer' WHERE "id" = 191;
INSERT INTO "public"."skills" (id, name) VALUES (196, 'Charity Worker');
INSERT INTO "public"."skills" (id, name) VALUES (197, 'Chartered');
INSERT INTO "public"."skills" (id, name) VALUES (198, 'Chartered Accountant');
INSERT INTO "public"."skills" (id, name) VALUES (199, 'Chauffeur');
INSERT INTO "public"."skills" (id, name) VALUES (200, 'Chef');
INSERT INTO "public"."skills" (id, name) VALUES (201, 'Chemist');
INSERT INTO "public"."skills" (id, name) VALUES (202, 'Chicken Chaser');
INSERT INTO "public"."skills" (id, name) VALUES (203, 'Child Minder');
INSERT INTO "public"."skills" (id, name) VALUES (204, 'Childminder');
INSERT INTO "public"."skills" (id, name) VALUES (205, 'Chimney Sweep');
INSERT INTO "public"."skills" (id, name) VALUES (206, 'China Restorer');
INSERT INTO "public"."skills" (id, name) VALUES (207, 'Chiropodist');
INSERT INTO "public"."skills" (id, name) VALUES (208, 'Chiropractor');
INSERT INTO "public"."skills" (id, name) VALUES (209, 'Choreographer');
INSERT INTO "public"."skills" (id, name) VALUES (210, 'Church Officer');
INSERT INTO "public"."skills" (id, name) VALUES (211, 'Church Warden');
INSERT INTO "public"."skills" (id, name) VALUES (212, 'Cinema Manager');
INSERT INTO "public"."skills" (id, name) VALUES (213, 'Circus Proprietor');
INSERT INTO "public"."skills" (id, name) VALUES (214, 'Circus Worker');
INSERT INTO "public"."skills" (id, name) VALUES (215, 'Civil Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (216, 'Civil Servant');
INSERT INTO "public"."skills" (id, name) VALUES (217, 'Claims Adjustor');
INSERT INTO "public"."skills" (id, name) VALUES (218, 'Claims Assessor');
INSERT INTO "public"."skills" (id, name) VALUES (219, 'Claims Manager');
INSERT INTO "public"."skills" (id, name) VALUES (220, 'Clairvoyant');
INSERT INTO "public"."skills" (id, name) VALUES (221, 'Classroom Aide');
INSERT INTO "public"."skills" (id, name) VALUES (222, 'Cleaner');
INSERT INTO "public"."skills" (id, name) VALUES (223, 'Clergyman');
INSERT INTO "public"."skills" (id, name) VALUES (224, 'Cleric');
INSERT INTO "public"."skills" (id, name) VALUES (225, 'Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (226, 'Commissioned');
INSERT INTO "public"."skills" (id, name) VALUES (227, 'Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (228, 'Coroner');
INSERT INTO "public"."skills" (id, name) VALUES (229, 'Councillor');
INSERT INTO "public"."skills" (id, name) VALUES (230, 'Counsellor');
INSERT INTO "public"."skills" (id, name) VALUES (231, 'Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (232, 'Decorator');
INSERT INTO "public"."skills" (id, name) VALUES (233, 'Delivery Driver');
INSERT INTO "public"."skills" (id, name) VALUES (234, 'Doctor');
INSERT INTO "public"."skills" (id, name) VALUES (235, 'Driver');
INSERT INTO "public"."skills" (id, name) VALUES (236, 'Economist');
INSERT INTO "public"."skills" (id, name) VALUES (237, 'Editor');
INSERT INTO "public"."skills" (id, name) VALUES (238, 'Employee');
INSERT INTO "public"."skills" (id, name) VALUES (239, 'Employment');
INSERT INTO "public"."skills" (id, name) VALUES (240, 'Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (241, 'English Teacher');
INSERT INTO "public"."skills" (id, name) VALUES (242, 'Entertainer');
INSERT INTO "public"."skills" (id, name) VALUES (243, 'Envoy');
INSERT INTO "public"."skills" (id, name) VALUES (244, 'Executive');
INSERT INTO "public"."skills" (id, name) VALUES (245, 'Farmer');
INSERT INTO "public"."skills" (id, name) VALUES (246, 'Fireman');
INSERT INTO "public"."skills" (id, name) VALUES (247, 'Floor Layer');
INSERT INTO "public"."skills" (id, name) VALUES (248, 'Floor Manager');
INSERT INTO "public"."skills" (id, name) VALUES (249, 'Florist');
INSERT INTO "public"."skills" (id, name) VALUES (250, 'Flour Miller');
INSERT INTO "public"."skills" (id, name) VALUES (251, 'Flower Arranger');
INSERT INTO "public"."skills" (id, name) VALUES (252, 'Flying Instructor');
INSERT INTO "public"."skills" (id, name) VALUES (253, 'Foam Convertor');
INSERT INTO "public"."skills" (id, name) VALUES (254, 'Food Processor');
INSERT INTO "public"."skills" (id, name) VALUES (255, 'Footballer');
INSERT INTO "public"."skills" (id, name) VALUES (256, 'Foreman');
INSERT INTO "public"."skills" (id, name) VALUES (257, 'Forensic Scientist');
INSERT INTO "public"."skills" (id, name) VALUES (258, 'Forest Ranger');
INSERT INTO "public"."skills" (id, name) VALUES (259, 'Forester');
INSERT INTO "public"."skills" (id, name) VALUES (260, 'Fork Lift Truck Driver');
INSERT INTO "public"."skills" (id, name) VALUES (261, 'Forwarding Agent');
INSERT INTO "public"."skills" (id, name) VALUES (262, 'Foster Parent');
INSERT INTO "public"."skills" (id, name) VALUES (263, 'Foundry Worker');
INSERT INTO "public"."skills" (id, name) VALUES (264, 'Fraud Investigator');
INSERT INTO "public"."skills" (id, name) VALUES (265, 'French Polisher');
INSERT INTO "public"."skills" (id, name) VALUES (266, 'Fruiterer');
INSERT INTO "public"."skills" (id, name) VALUES (267, 'Fuel Merchant');
INSERT INTO "public"."skills" (id, name) VALUES (268, 'Fund Raiser');
INSERT INTO "public"."skills" (id, name) VALUES (269, 'Funeral Director');
INSERT INTO "public"."skills" (id, name) VALUES (270, 'Funeral Furnisher');
INSERT INTO "public"."skills" (id, name) VALUES (271, 'Furnace Man');
INSERT INTO "public"."skills" (id, name) VALUES (272, 'Furniture Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (273, 'Furniture Remover');
INSERT INTO "public"."skills" (id, name) VALUES (274, 'Furniture Restorer');
INSERT INTO "public"."skills" (id, name) VALUES (275, 'Furrier');
INSERT INTO "public"."skills" (id, name) VALUES (276, 'Gallery Owner');
INSERT INTO "public"."skills" (id, name) VALUES (277, 'Gambler');
INSERT INTO "public"."skills" (id, name) VALUES (278, 'Gamekeeper');
INSERT INTO "public"."skills" (id, name) VALUES (279, 'Gaming Board Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (280, 'Gaming Club Manager');
INSERT INTO "public"."skills" (id, name) VALUES (281, 'Gaming Club Proprietor');
INSERT INTO "public"."skills" (id, name) VALUES (282, 'Garage Attendant');
INSERT INTO "public"."skills" (id, name) VALUES (283, 'Garage Foreman');
INSERT INTO "public"."skills" (id, name) VALUES (284, 'Garage Manager');
INSERT INTO "public"."skills" (id, name) VALUES (285, 'Garda');
INSERT INTO "public"."skills" (id, name) VALUES (286, 'Garden Designer');
INSERT INTO "public"."skills" (id, name) VALUES (287, 'Gardener');
INSERT INTO "public"."skills" (id, name) VALUES (288, 'Gas Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (289, 'Gas Mechanic');
INSERT INTO "public"."skills" (id, name) VALUES (290, 'Gas Technician');
INSERT INTO "public"."skills" (id, name) VALUES (291, 'Gate Keeper');
INSERT INTO "public"."skills" (id, name) VALUES (292, 'Genealogist');
INSERT INTO "public"."skills" (id, name) VALUES (293, 'General Practitioner');
INSERT INTO "public"."skills" (id, name) VALUES (294, 'Geologist');
INSERT INTO "public"."skills" (id, name) VALUES (295, 'Geophysicist');
INSERT INTO "public"."skills" (id, name) VALUES (296, 'Gilder');
INSERT INTO "public"."skills" (id, name) VALUES (297, 'Glass Worker');
INSERT INTO "public"."skills" (id, name) VALUES (298, 'Glazier');
INSERT INTO "public"."skills" (id, name) VALUES (299, 'Goldsmith');
INSERT INTO "public"."skills" (id, name) VALUES (300, 'Golf Caddy');
INSERT INTO "public"."skills" (id, name) VALUES (301, 'Golf Club Professional');
INSERT INTO "public"."skills" (id, name) VALUES (302, 'Golfer');
INSERT INTO "public"."skills" (id, name) VALUES (303, 'Goods Handler');
INSERT INTO "public"."skills" (id, name) VALUES (304, 'Governor');
INSERT INTO "public"."skills" (id, name) VALUES (305, 'Granite Technician');
INSERT INTO "public"."skills" (id, name) VALUES (306, 'Graphic Designer');
INSERT INTO "public"."skills" (id, name) VALUES (307, 'Graphologist');
INSERT INTO "public"."skills" (id, name) VALUES (308, 'Grave Digger');
INSERT INTO "public"."skills" (id, name) VALUES (309, 'Gravel Merchant');
INSERT INTO "public"."skills" (id, name) VALUES (310, 'Green Keeper');
INSERT INTO "public"."skills" (id, name) VALUES (311, 'Greengrocer');
INSERT INTO "public"."skills" (id, name) VALUES (312, 'Grocer');
INSERT INTO "public"."skills" (id, name) VALUES (313, 'Groom');
INSERT INTO "public"."skills" (id, name) VALUES (314, 'Ground Worker');
INSERT INTO "public"."skills" (id, name) VALUES (315, 'Groundsman');
INSERT INTO "public"."skills" (id, name) VALUES (316, 'Guest House Owner');
INSERT INTO "public"."skills" (id, name) VALUES (317, 'Guest House Proprietor');
INSERT INTO "public"."skills" (id, name) VALUES (318, 'Gun Smith');
INSERT INTO "public"."skills" (id, name) VALUES (319, 'Gynaecologist');
INSERT INTO "public"."skills" (id, name) VALUES (320, 'HGV Driver');
INSERT INTO "public"."skills" (id, name) VALUES (321, 'HGV Mechanic');
INSERT INTO "public"."skills" (id, name) VALUES (322, 'Hairdresser');
INSERT INTO "public"."skills" (id, name) VALUES (323, 'Handyman');
INSERT INTO "public"."skills" (id, name) VALUES (324, 'Hardware Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (325, 'Haulage Contractor');
INSERT INTO "public"."skills" (id, name) VALUES (326, 'Hawker');
INSERT INTO "public"."skills" (id, name) VALUES (327, 'Health Advisor');
INSERT INTO "public"."skills" (id, name) VALUES (328, 'Health And Safety');
INSERT INTO "public"."skills" (id, name) VALUES (329, 'Health Care Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (330, 'Health Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (331, 'Health Nurse');
INSERT INTO "public"."skills" (id, name) VALUES (332, 'Health Planner');
INSERT INTO "public"."skills" (id, name) VALUES (333, 'Health Service');
INSERT INTO "public"."skills" (id, name) VALUES (334, 'Health Therapist');
INSERT INTO "public"."skills" (id, name) VALUES (335, 'Health Visitor');
INSERT INTO "public"."skills" (id, name) VALUES (336, 'Hearing Therapist');
INSERT INTO "public"."skills" (id, name) VALUES (337, 'Heating Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (338, 'Herbalist');
INSERT INTO "public"."skills" (id, name) VALUES (339, 'Highway Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (340, 'Hire Car Driver');
INSERT INTO "public"."skills" (id, name) VALUES (341, 'Historian');
INSERT INTO "public"."skills" (id, name) VALUES (342, 'History Teacher');
INSERT INTO "public"."skills" (id, name) VALUES (343, 'Hod Carrier');
INSERT INTO "public"."skills" (id, name) VALUES (344, 'Home Economist');
INSERT INTO "public"."skills" (id, name) VALUES (345, 'Home Help');
INSERT INTO "public"."skills" (id, name) VALUES (346, 'Homecare Manager');
INSERT INTO "public"."skills" (id, name) VALUES (347, 'Homeopath');
INSERT INTO "public"."skills" (id, name) VALUES (348, 'Homeworker');
INSERT INTO "public"."skills" (id, name) VALUES (349, 'Hop Merchant');
INSERT INTO "public"."skills" (id, name) VALUES (350, 'Horse Breeder');
INSERT INTO "public"."skills" (id, name) VALUES (351, 'Horse Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (352, 'Horse Riding Instructor');
INSERT INTO "public"."skills" (id, name) VALUES (353, 'Horse Trader');
INSERT INTO "public"."skills" (id, name) VALUES (354, 'Horse Trainer');
INSERT INTO "public"."skills" (id, name) VALUES (355, 'Horticultural Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (356, 'Horticulturalist');
INSERT INTO "public"."skills" (id, name) VALUES (357, 'Hosiery Mechanic');
INSERT INTO "public"."skills" (id, name) VALUES (358, 'Hosiery Worker');
INSERT INTO "public"."skills" (id, name) VALUES (359, 'Hospital Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (360, 'Hospital Doctor');
INSERT INTO "public"."skills" (id, name) VALUES (361, 'Hospital Manager');
INSERT INTO "public"."skills" (id, name) VALUES (362, 'Hospital Orderly');
INSERT INTO "public"."skills" (id, name) VALUES (363, 'Hospital Technician');
INSERT INTO "public"."skills" (id, name) VALUES (364, 'Hospital Warden');
INSERT INTO "public"."skills" (id, name) VALUES (365, 'Hospital Worker');
INSERT INTO "public"."skills" (id, name) VALUES (366, 'Hostess');
INSERT INTO "public"."skills" (id, name) VALUES (367, 'Hot Foil Printer');
INSERT INTO "public"."skills" (id, name) VALUES (368, 'Hotel Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (369, 'Hotel Worker');
INSERT INTO "public"."skills" (id, name) VALUES (370, 'Hotelier');
INSERT INTO "public"."skills" (id, name) VALUES (371, 'Househusband');
INSERT INTO "public"."skills" (id, name) VALUES (372, 'Housekeeper');
INSERT INTO "public"."skills" (id, name) VALUES (373, 'Housewife');
INSERT INTO "public"."skills" (id, name) VALUES (374, 'Housing Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (375, 'Housing Officer');
INSERT INTO "public"."skills" (id, name) VALUES (376, 'Housing Supervisor');
INSERT INTO "public"."skills" (id, name) VALUES (377, 'Hygienist');
INSERT INTO "public"."skills" (id, name) VALUES (378, 'Hypnotherapist');
INSERT INTO "public"."skills" (id, name) VALUES (379, 'Hypnotist');
INSERT INTO "public"."skills" (id, name) VALUES (380, 'IT Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (381, 'IT Manager');
INSERT INTO "public"."skills" (id, name) VALUES (382, 'IT Trainer');
INSERT INTO "public"."skills" (id, name) VALUES (383, 'Ice Cream Vendor');
INSERT INTO "public"."skills" (id, name) VALUES (384, 'Illustrator');
INSERT INTO "public"."skills" (id, name) VALUES (385, 'Immigration Officer');
INSERT INTO "public"."skills" (id, name) VALUES (386, 'Import Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (387, 'Importer');
INSERT INTO "public"."skills" (id, name) VALUES (388, 'Independent Means');
INSERT INTO "public"."skills" (id, name) VALUES (389, 'Induction Moulder');
INSERT INTO "public"."skills" (id, name) VALUES (390, 'Industrial Chemist');
INSERT INTO "public"."skills" (id, name) VALUES (391, 'Industrial Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (392, 'Injection Moulder');
INSERT INTO "public"."skills" (id, name) VALUES (393, 'Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (394, 'Instructor');
INSERT INTO "public"."skills" (id, name) VALUES (395, 'Instrument Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (396, 'Instrument Maker');
INSERT INTO "public"."skills" (id, name) VALUES (397, 'Instrument Supervisor');
INSERT INTO "public"."skills" (id, name) VALUES (398, 'Instrument Technician');
INSERT INTO "public"."skills" (id, name) VALUES (399, 'Insurance Agent');
INSERT INTO "public"."skills" (id, name) VALUES (400, 'Insurance Assessor');
INSERT INTO "public"."skills" (id, name) VALUES (401, 'Insurance Broker');
INSERT INTO "public"."skills" (id, name) VALUES (402, 'Insurance Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (403, 'Insurance Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (404, 'Insurance Staff');
INSERT INTO "public"."skills" (id, name) VALUES (405, 'Interior Decorator');
INSERT INTO "public"."skills" (id, name) VALUES (406, 'Interior Designer');
INSERT INTO "public"."skills" (id, name) VALUES (407, 'Interpreter');
INSERT INTO "public"."skills" (id, name) VALUES (408, 'Interviewer');
INSERT INTO "public"."skills" (id, name) VALUES (409, 'Inventor');
INSERT INTO "public"."skills" (id, name) VALUES (410, 'Investigator');
INSERT INTO "public"."skills" (id, name) VALUES (411, 'Investment Advisor');
INSERT INTO "public"."skills" (id, name) VALUES (412, 'Investment Banker');
INSERT INTO "public"."skills" (id, name) VALUES (413, 'Investment Manager');
INSERT INTO "public"."skills" (id, name) VALUES (414, 'Investment Strategist');
INSERT INTO "public"."skills" (id, name) VALUES (415, 'Ironmonger');
INSERT INTO "public"."skills" (id, name) VALUES (416, 'Janitor');
INSERT INTO "public"."skills" (id, name) VALUES (417, 'Jazz Composer');
INSERT INTO "public"."skills" (id, name) VALUES (418, 'Jeweller');
INSERT INTO "public"."skills" (id, name) VALUES (419, 'Jewellery');
INSERT INTO "public"."skills" (id, name) VALUES (420, 'Jockey');
INSERT INTO "public"."skills" (id, name) VALUES (421, 'Joiner');
INSERT INTO "public"."skills" (id, name) VALUES (422, 'Joinery Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (423, 'Journalist');
INSERT INTO "public"."skills" (id, name) VALUES (424, 'Judge');
INSERT INTO "public"."skills" (id, name) VALUES (425, 'Keep Fit Instructor');
INSERT INTO "public"."skills" (id, name) VALUES (426, 'Kennel Hand');
INSERT INTO "public"."skills" (id, name) VALUES (427, 'Kitchen Worker');
INSERT INTO "public"."skills" (id, name) VALUES (428, 'Knitter');
INSERT INTO "public"."skills" (id, name) VALUES (429, 'Labelling Operator');
INSERT INTO "public"."skills" (id, name) VALUES (430, 'Laboratory Analyst');
INSERT INTO "public"."skills" (id, name) VALUES (431, 'Labourer');
INSERT INTO "public"."skills" (id, name) VALUES (432, 'Laminator');
INSERT INTO "public"."skills" (id, name) VALUES (433, 'Lampshade Maker');
INSERT INTO "public"."skills" (id, name) VALUES (434, 'Land Agent');
INSERT INTO "public"."skills" (id, name) VALUES (435, 'Land Surveyor');
INSERT INTO "public"."skills" (id, name) VALUES (436, 'Landlady');
INSERT INTO "public"."skills" (id, name) VALUES (437, 'Landlord');
INSERT INTO "public"."skills" (id, name) VALUES (438, 'Landowner');
INSERT INTO "public"."skills" (id, name) VALUES (439, 'Landworker');
INSERT INTO "public"."skills" (id, name) VALUES (440, 'Lathe Operator');
INSERT INTO "public"."skills" (id, name) VALUES (441, 'Laundry Staff');
INSERT INTO "public"."skills" (id, name) VALUES (442, 'Laundry Worker');
INSERT INTO "public"."skills" (id, name) VALUES (443, 'Lavatory Attendant');
INSERT INTO "public"."skills" (id, name) VALUES (444, 'Law Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (445, 'Lawn Mower');
INSERT INTO "public"."skills" (id, name) VALUES (446, 'Lawyer');
INSERT INTO "public"."skills" (id, name) VALUES (447, 'Leaflet Distributor');
INSERT INTO "public"."skills" (id, name) VALUES (448, 'Leather Worker');
INSERT INTO "public"."skills" (id, name) VALUES (449, 'Lecturer');
INSERT INTO "public"."skills" (id, name) VALUES (450, 'Ledger Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (451, 'Legal Advisor');
INSERT INTO "public"."skills" (id, name) VALUES (452, 'Legal Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (453, 'Legal Executive');
INSERT INTO "public"."skills" (id, name) VALUES (454, 'Legal Secretary');
INSERT INTO "public"."skills" (id, name) VALUES (455, 'Letting Agent');
INSERT INTO "public"."skills" (id, name) VALUES (456, 'Liaison Officer');
INSERT INTO "public"."skills" (id, name) VALUES (457, 'Librarian');
INSERT INTO "public"."skills" (id, name) VALUES (458, 'Library Manager');
INSERT INTO "public"."skills" (id, name) VALUES (459, 'Licensed Premises');
INSERT INTO "public"."skills" (id, name) VALUES (460, 'Licensee');
INSERT INTO "public"."skills" (id, name) VALUES (461, 'Licensing');
INSERT INTO "public"."skills" (id, name) VALUES (462, 'Lifeguard');
INSERT INTO "public"."skills" (id, name) VALUES (463, 'Lift Attendant');
INSERT INTO "public"."skills" (id, name) VALUES (464, 'Lift Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (465, 'Lighterman');
INSERT INTO "public"."skills" (id, name) VALUES (466, 'Lighthouse Keeper');
INSERT INTO "public"."skills" (id, name) VALUES (467, 'Lighting Designer');
INSERT INTO "public"."skills" (id, name) VALUES (468, 'Lighting Technician');
INSERT INTO "public"."skills" (id, name) VALUES (469, 'Lime Kiln Attendant');
INSERT INTO "public"."skills" (id, name) VALUES (470, 'Line Manager');
INSERT INTO "public"."skills" (id, name) VALUES (471, 'Line Worker');
INSERT INTO "public"."skills" (id, name) VALUES (472, 'Lineman');
INSERT INTO "public"."skills" (id, name) VALUES (473, 'Linguist');
INSERT INTO "public"."skills" (id, name) VALUES (474, 'Literary Agent');
INSERT INTO "public"."skills" (id, name) VALUES (475, 'Literary Editor');
INSERT INTO "public"."skills" (id, name) VALUES (476, 'Lithographer');
INSERT INTO "public"."skills" (id, name) VALUES (477, 'Litigation Manager');
INSERT INTO "public"."skills" (id, name) VALUES (478, 'Loans Manager');
INSERT INTO "public"."skills" (id, name) VALUES (479, 'Local Government');
INSERT INTO "public"."skills" (id, name) VALUES (480, 'Lock Keeper');
INSERT INTO "public"."skills" (id, name) VALUES (481, 'Locksmith');
INSERT INTO "public"."skills" (id, name) VALUES (482, 'Locum Pharmacist');
INSERT INTO "public"."skills" (id, name) VALUES (483, 'Log Merchant');
INSERT INTO "public"."skills" (id, name) VALUES (484, 'Lorry Driver');
INSERT INTO "public"."skills" (id, name) VALUES (485, 'Loss Adjustor');
INSERT INTO "public"."skills" (id, name) VALUES (486, 'Loss Assessor');
INSERT INTO "public"."skills" (id, name) VALUES (487, 'Lumberjack');
INSERT INTO "public"."skills" (id, name) VALUES (488, 'Machine Fitters');
INSERT INTO "public"."skills" (id, name) VALUES (489, 'Machine Minder');
INSERT INTO "public"."skills" (id, name) VALUES (490, 'Machine Operator');
INSERT INTO "public"."skills" (id, name) VALUES (491, 'Machine Setter');
INSERT INTO "public"."skills" (id, name) VALUES (492, 'Machine Tool');
INSERT INTO "public"."skills" (id, name) VALUES (493, 'Machine Tool Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (494, 'Machinist');
INSERT INTO "public"."skills" (id, name) VALUES (495, 'Magician');
INSERT INTO "public"."skills" (id, name) VALUES (496, 'Magistrate');
INSERT INTO "public"."skills" (id, name) VALUES (497, 'Magistrates Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (498, 'Maid');
INSERT INTO "public"."skills" (id, name) VALUES (499, 'Maintenance Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (500, 'Make Up Artist');
INSERT INTO "public"."skills" (id, name) VALUES (501, 'Manicurist');
INSERT INTO "public"."skills" (id, name) VALUES (502, 'Manufacturing');
INSERT INTO "public"."skills" (id, name) VALUES (503, 'Map Mounter');
INSERT INTO "public"."skills" (id, name) VALUES (504, 'Marble Finisher');
INSERT INTO "public"."skills" (id, name) VALUES (505, 'Marble Mason');
INSERT INTO "public"."skills" (id, name) VALUES (506, 'Marine Broker');
INSERT INTO "public"."skills" (id, name) VALUES (507, 'Marine Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (508, 'Marine Electrician');
INSERT INTO "public"."skills" (id, name) VALUES (509, 'Marine Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (510, 'Marine Geologist');
INSERT INTO "public"."skills" (id, name) VALUES (511, 'Marine Pilot');
INSERT INTO "public"."skills" (id, name) VALUES (512, 'Marine Surveyor');
INSERT INTO "public"."skills" (id, name) VALUES (513, 'Market Gardener');
INSERT INTO "public"."skills" (id, name) VALUES (514, 'Market Research');
INSERT INTO "public"."skills" (id, name) VALUES (515, 'Market Researcher');
INSERT INTO "public"."skills" (id, name) VALUES (516, 'Market Trader');
INSERT INTO "public"."skills" (id, name) VALUES (517, 'Marketing Agent');
INSERT INTO "public"."skills" (id, name) VALUES (518, 'Marketing Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (519, 'Marketing Coordinator');
INSERT INTO "public"."skills" (id, name) VALUES (520, 'Marketing Director');
INSERT INTO "public"."skills" (id, name) VALUES (521, 'Marketing Manager');
INSERT INTO "public"."skills" (id, name) VALUES (522, 'Marquee Erector');
INSERT INTO "public"."skills" (id, name) VALUES (523, 'Massage Therapist');
INSERT INTO "public"."skills" (id, name) VALUES (524, 'Masseur');
INSERT INTO "public"."skills" (id, name) VALUES (525, 'Masseuse');
INSERT INTO "public"."skills" (id, name) VALUES (526, 'Master Mariner');
INSERT INTO "public"."skills" (id, name) VALUES (527, 'Materials Controller');
INSERT INTO "public"."skills" (id, name) VALUES (528, 'Materials Manager');
INSERT INTO "public"."skills" (id, name) VALUES (529, 'Mathematician');
INSERT INTO "public"."skills" (id, name) VALUES (530, 'Maths Teacher');
INSERT INTO "public"."skills" (id, name) VALUES (531, 'Matron');
INSERT INTO "public"."skills" (id, name) VALUES (532, 'Mattress Maker');
INSERT INTO "public"."skills" (id, name) VALUES (533, 'Meat Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (534, 'Meat Wholesaler');
INSERT INTO "public"."skills" (id, name) VALUES (535, 'Mechanic');
INSERT INTO "public"."skills" (id, name) VALUES (536, 'Medal Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (537, 'Medical Advisor');
INSERT INTO "public"."skills" (id, name) VALUES (538, 'Medical Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (539, 'Medical Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (540, 'Medical Officer');
INSERT INTO "public"."skills" (id, name) VALUES (541, 'Medical Physicist');
INSERT INTO "public"."skills" (id, name) VALUES (542, 'Medical Practitioner');
INSERT INTO "public"."skills" (id, name) VALUES (543, 'Medical Researcher');
INSERT INTO "public"."skills" (id, name) VALUES (544, 'Medical Secretary');
INSERT INTO "public"."skills" (id, name) VALUES (545, 'Medical Student');
INSERT INTO "public"."skills" (id, name) VALUES (546, 'Medical Supplier');
INSERT INTO "public"."skills" (id, name) VALUES (547, 'Medical Technician');
INSERT INTO "public"."skills" (id, name) VALUES (548, 'Merchandiser');
INSERT INTO "public"."skills" (id, name) VALUES (549, 'Merchant');
INSERT INTO "public"."skills" (id, name) VALUES (550, 'Merchant Banker');
INSERT INTO "public"."skills" (id, name) VALUES (551, 'Merchant Seaman');
INSERT INTO "public"."skills" (id, name) VALUES (552, 'Messenger');
INSERT INTO "public"."skills" (id, name) VALUES (553, 'Metal Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (554, 'Metal Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (555, 'Metal Polisher');
INSERT INTO "public"."skills" (id, name) VALUES (556, 'Metal Worker');
INSERT INTO "public"."skills" (id, name) VALUES (557, 'Metallurgist');
INSERT INTO "public"."skills" (id, name) VALUES (558, 'Meteorologist');
INSERT INTO "public"."skills" (id, name) VALUES (559, 'Meter Reader');
INSERT INTO "public"."skills" (id, name) VALUES (560, 'Microbiologist');
INSERT INTO "public"."skills" (id, name) VALUES (561, 'Midwife');
INSERT INTO "public"."skills" (id, name) VALUES (562, 'Military Leader');
INSERT INTO "public"."skills" (id, name) VALUES (563, 'Milklady');
INSERT INTO "public"."skills" (id, name) VALUES (564, 'Milkman');
INSERT INTO "public"."skills" (id, name) VALUES (565, 'Mill Operator');
INSERT INTO "public"."skills" (id, name) VALUES (566, 'Mill Worker');
INSERT INTO "public"."skills" (id, name) VALUES (567, 'Miller');
INSERT INTO "public"."skills" (id, name) VALUES (568, 'Milliner');
INSERT INTO "public"."skills" (id, name) VALUES (569, 'Millwright');
INSERT INTO "public"."skills" (id, name) VALUES (570, 'Miner');
INSERT INTO "public"."skills" (id, name) VALUES (571, 'Mineralologist');
INSERT INTO "public"."skills" (id, name) VALUES (572, 'Minibus Driver');
INSERT INTO "public"."skills" (id, name) VALUES (573, 'Minicab Driver');
INSERT INTO "public"."skills" (id, name) VALUES (574, 'Mining Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (575, 'Mining Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (576, 'Money Broker');
INSERT INTO "public"."skills" (id, name) VALUES (577, 'Moneylender');
INSERT INTO "public"."skills" (id, name) VALUES (578, 'Mooring Contractor');
INSERT INTO "public"."skills" (id, name) VALUES (579, 'Mortgage Broker');
INSERT INTO "public"."skills" (id, name) VALUES (580, 'Mortician');
INSERT INTO "public"."skills" (id, name) VALUES (581, 'Motor Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (582, 'Motor Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (583, 'Motor Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (584, 'Motor Mechanic');
INSERT INTO "public"."skills" (id, name) VALUES (585, 'Motor Racing');
INSERT INTO "public"."skills" (id, name) VALUES (586, 'Motor Trader');
INSERT INTO "public"."skills" (id, name) VALUES (587, 'Museum Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (588, 'Museum Attendant');
INSERT INTO "public"."skills" (id, name) VALUES (589, 'Music Teacher');
INSERT INTO "public"."skills" (id, name) VALUES (590, 'Musician');
INSERT INTO "public"."skills" (id, name) VALUES (591, 'Nanny');
INSERT INTO "public"."skills" (id, name) VALUES (592, 'Navigator');
INSERT INTO "public"."skills" (id, name) VALUES (593, 'Negotiator');
INSERT INTO "public"."skills" (id, name) VALUES (594, 'Neurologist');
INSERT INTO "public"."skills" (id, name) VALUES (595, 'Newsagent');
INSERT INTO "public"."skills" (id, name) VALUES (596, 'Night Porter');
INSERT INTO "public"."skills" (id, name) VALUES (597, 'Night Watchman');
INSERT INTO "public"."skills" (id, name) VALUES (598, 'Nuclear Scientist');
INSERT INTO "public"."skills" (id, name) VALUES (599, 'Nun');
INSERT INTO "public"."skills" (id, name) VALUES (600, 'Nurse');
INSERT INTO "public"."skills" (id, name) VALUES (601, 'Nursery Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (602, 'Nursery Nurse');
INSERT INTO "public"."skills" (id, name) VALUES (603, 'Nursery Worker');
INSERT INTO "public"."skills" (id, name) VALUES (604, 'Nurseryman');
INSERT INTO "public"."skills" (id, name) VALUES (605, 'Nursing Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (606, 'Nursing Auxiliary');
INSERT INTO "public"."skills" (id, name) VALUES (607, 'Nursing Manager');
INSERT INTO "public"."skills" (id, name) VALUES (608, 'Nursing Sister');
INSERT INTO "public"."skills" (id, name) VALUES (609, 'Nutritionist');
INSERT INTO "public"."skills" (id, name) VALUES (610, 'Off Shore');
INSERT INTO "public"."skills" (id, name) VALUES (611, 'Office Manager');
INSERT INTO "public"."skills" (id, name) VALUES (612, 'Office Worker');
INSERT INTO "public"."skills" (id, name) VALUES (613, 'Oil Broker');
INSERT INTO "public"."skills" (id, name) VALUES (614, 'Oil Rig Crew');
INSERT INTO "public"."skills" (id, name) VALUES (615, 'Opera Singer');
INSERT INTO "public"."skills" (id, name) VALUES (616, 'Operations');
INSERT INTO "public"."skills" (id, name) VALUES (617, 'Operative');
INSERT INTO "public"."skills" (id, name) VALUES (618, 'Operator');
INSERT INTO "public"."skills" (id, name) VALUES (619, 'Optical');
INSERT INTO "public"."skills" (id, name) VALUES (620, 'Optical Advisor');
INSERT INTO "public"."skills" (id, name) VALUES (621, 'Optical Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (622, 'Optician');
INSERT INTO "public"."skills" (id, name) VALUES (623, 'Optometrist');
INSERT INTO "public"."skills" (id, name) VALUES (624, 'Orchestral');
INSERT INTO "public"."skills" (id, name) VALUES (625, 'Organiser');
INSERT INTO "public"."skills" (id, name) VALUES (626, 'Organist');
INSERT INTO "public"."skills" (id, name) VALUES (627, 'Ornamental');
INSERT INTO "public"."skills" (id, name) VALUES (628, 'Ornithologist');
INSERT INTO "public"."skills" (id, name) VALUES (629, 'Orthopaedic');
INSERT INTO "public"."skills" (id, name) VALUES (630, 'Orthoptist');
INSERT INTO "public"."skills" (id, name) VALUES (631, 'Osteopath');
INSERT INTO "public"."skills" (id, name) VALUES (632, 'Outdoor Pursuits');
INSERT INTO "public"."skills" (id, name) VALUES (633, 'Outreach Worker');
INSERT INTO "public"."skills" (id, name) VALUES (634, 'Packaging');
INSERT INTO "public"."skills" (id, name) VALUES (635, 'Packer');
INSERT INTO "public"."skills" (id, name) VALUES (636, 'Paediatrician');
INSERT INTO "public"."skills" (id, name) VALUES (637, 'Paint Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (638, 'Painter');
INSERT INTO "public"."skills" (id, name) VALUES (639, 'Palaeobotanist');
INSERT INTO "public"."skills" (id, name) VALUES (640, 'Palaeontologist');
INSERT INTO "public"."skills" (id, name) VALUES (641, 'Pallet Maker');
INSERT INTO "public"."skills" (id, name) VALUES (642, 'Panel Beater');
INSERT INTO "public"."skills" (id, name) VALUES (643, 'Paramedic');
INSERT INTO "public"."skills" (id, name) VALUES (644, 'Park Attendant');
INSERT INTO "public"."skills" (id, name) VALUES (645, 'Park Keeper');
INSERT INTO "public"."skills" (id, name) VALUES (646, 'Park Ranger');
INSERT INTO "public"."skills" (id, name) VALUES (647, 'Partition Erector');
INSERT INTO "public"."skills" (id, name) VALUES (648, 'Parts Man');
INSERT INTO "public"."skills" (id, name) VALUES (649, 'Parts Manager');
INSERT INTO "public"."skills" (id, name) VALUES (650, 'Parts Supervisor');
INSERT INTO "public"."skills" (id, name) VALUES (651, 'Party Planner');
INSERT INTO "public"."skills" (id, name) VALUES (652, 'Pasteuriser');
INSERT INTO "public"."skills" (id, name) VALUES (653, 'Pastry Chef');
INSERT INTO "public"."skills" (id, name) VALUES (654, 'Patent Agent');
INSERT INTO "public"."skills" (id, name) VALUES (655, 'Patent Attorney');
INSERT INTO "public"."skills" (id, name) VALUES (656, 'Pathologist');
INSERT INTO "public"."skills" (id, name) VALUES (657, 'Patrolman');
INSERT INTO "public"."skills" (id, name) VALUES (658, 'Pattern Cutter');
INSERT INTO "public"."skills" (id, name) VALUES (659, 'Pattern Maker');
INSERT INTO "public"."skills" (id, name) VALUES (660, 'Pattern Weaver');
INSERT INTO "public"."skills" (id, name) VALUES (661, 'Pawnbroker');
INSERT INTO "public"."skills" (id, name) VALUES (662, 'Payroll Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (663, 'Payroll Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (664, 'Payroll Manager');
INSERT INTO "public"."skills" (id, name) VALUES (665, 'Payroll Supervisor');
INSERT INTO "public"."skills" (id, name) VALUES (666, 'Personnel Officer');
INSERT INTO "public"."skills" (id, name) VALUES (667, 'Pest Controller');
INSERT INTO "public"."skills" (id, name) VALUES (668, 'Pet Minder');
INSERT INTO "public"."skills" (id, name) VALUES (669, 'Pharmacist');
INSERT INTO "public"."skills" (id, name) VALUES (670, 'Philatelist');
INSERT INTO "public"."skills" (id, name) VALUES (671, 'Photographer');
INSERT INTO "public"."skills" (id, name) VALUES (672, 'Physician');
INSERT INTO "public"."skills" (id, name) VALUES (673, 'Physicist');
INSERT INTO "public"."skills" (id, name) VALUES (674, 'Physiologist');
INSERT INTO "public"."skills" (id, name) VALUES (675, 'Physiotherapist');
INSERT INTO "public"."skills" (id, name) VALUES (676, 'Piano Teacher');
INSERT INTO "public"."skills" (id, name) VALUES (677, 'Piano Tuner');
INSERT INTO "public"."skills" (id, name) VALUES (678, 'Picture Editor');
INSERT INTO "public"."skills" (id, name) VALUES (679, 'Picture Framer');
INSERT INTO "public"."skills" (id, name) VALUES (680, 'Picture Reseacher');
INSERT INTO "public"."skills" (id, name) VALUES (681, 'Pig Man');
INSERT INTO "public"."skills" (id, name) VALUES (682, 'Pig Manager');
INSERT INTO "public"."skills" (id, name) VALUES (683, 'Pilot');
INSERT INTO "public"."skills" (id, name) VALUES (684, 'Pipe Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (685, 'Pipe Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (686, 'Pipe Insulator');
INSERT INTO "public"."skills" (id, name) VALUES (687, 'Pipe Layer');
INSERT INTO "public"."skills" (id, name) VALUES (688, 'Planning Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (689, 'Planning Manager');
INSERT INTO "public"."skills" (id, name) VALUES (690, 'Planning Officer');
INSERT INTO "public"."skills" (id, name) VALUES (691, 'Planning Technician');
INSERT INTO "public"."skills" (id, name) VALUES (692, 'Plant Attendant');
INSERT INTO "public"."skills" (id, name) VALUES (693, 'Plant Driver');
INSERT INTO "public"."skills" (id, name) VALUES (694, 'Plant Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (695, 'Plant Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (696, 'Plant Manager');
INSERT INTO "public"."skills" (id, name) VALUES (697, 'Plant Operator');
INSERT INTO "public"."skills" (id, name) VALUES (698, 'Plasterer');
INSERT INTO "public"."skills" (id, name) VALUES (699, 'Plastics Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (700, 'Plastics Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (701, 'Plate Layer');
INSERT INTO "public"."skills" (id, name) VALUES (702, 'Plater');
INSERT INTO "public"."skills" (id, name) VALUES (703, 'Playgroup Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (704, 'Playgroup Leader');
INSERT INTO "public"."skills" (id, name) VALUES (705, 'Plumber');
INSERT INTO "public"."skills" (id, name) VALUES (706, 'Podiatrist');
INSERT INTO "public"."skills" (id, name) VALUES (707, 'Police Officer');
INSERT INTO "public"."skills" (id, name) VALUES (708, 'Polisher');
INSERT INTO "public"."skills" (id, name) VALUES (709, 'Pool Attendant');
INSERT INTO "public"."skills" (id, name) VALUES (710, 'Pools Collector');
INSERT INTO "public"."skills" (id, name) VALUES (711, 'Porter');
INSERT INTO "public"."skills" (id, name) VALUES (712, 'Portfolio Manager');
INSERT INTO "public"."skills" (id, name) VALUES (713, 'Post Sorter');
INSERT INTO "public"."skills" (id, name) VALUES (714, 'Postman');
INSERT INTO "public"."skills" (id, name) VALUES (715, 'Postmaster');
INSERT INTO "public"."skills" (id, name) VALUES (716, 'Postwoman');
INSERT INTO "public"."skills" (id, name) VALUES (717, 'Potter');
INSERT INTO "public"."skills" (id, name) VALUES (718, 'Practice Manager');
INSERT INTO "public"."skills" (id, name) VALUES (719, 'Preacher');
INSERT INTO "public"."skills" (id, name) VALUES (720, 'Precision Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (721, 'Premises');
INSERT INTO "public"."skills" (id, name) VALUES (722, 'Premises Security');
INSERT INTO "public"."skills" (id, name) VALUES (723, 'Press Officer');
INSERT INTO "public"."skills" (id, name) VALUES (724, 'Press Operator');
INSERT INTO "public"."skills" (id, name) VALUES (725, 'Press Setter');
INSERT INTO "public"."skills" (id, name) VALUES (726, 'Presser');
INSERT INTO "public"."skills" (id, name) VALUES (727, 'Priest');
INSERT INTO "public"."skills" (id, name) VALUES (728, 'Print Finisher');
INSERT INTO "public"."skills" (id, name) VALUES (729, 'Printer');
INSERT INTO "public"."skills" (id, name) VALUES (730, 'Prison Chaplain');
INSERT INTO "public"."skills" (id, name) VALUES (731, 'Prison Officer');
INSERT INTO "public"."skills" (id, name) VALUES (732, 'Private Investigator');
INSERT INTO "public"."skills" (id, name) VALUES (733, 'Probation Officer');
INSERT INTO "public"."skills" (id, name) VALUES (734, 'Probation Worker');
INSERT INTO "public"."skills" (id, name) VALUES (735, 'Procurator Fiscal');
INSERT INTO "public"."skills" (id, name) VALUES (736, 'Produce Supervisor');
INSERT INTO "public"."skills" (id, name) VALUES (737, 'Producer');
INSERT INTO "public"."skills" (id, name) VALUES (738, 'Product Installer');
INSERT INTO "public"."skills" (id, name) VALUES (739, 'Product Manager');
INSERT INTO "public"."skills" (id, name) VALUES (740, 'Production Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (741, 'Production Hand');
INSERT INTO "public"."skills" (id, name) VALUES (742, 'Production Manager');
INSERT INTO "public"."skills" (id, name) VALUES (743, 'Production Planner');
INSERT INTO "public"."skills" (id, name) VALUES (744, 'Professional Boxer');
INSERT INTO "public"."skills" (id, name) VALUES (745, 'Professional Racing');
INSERT INTO "public"."skills" (id, name) VALUES (746, 'Professional Wrestler');
INSERT INTO "public"."skills" (id, name) VALUES (747, 'Progress Chaser');
INSERT INTO "public"."skills" (id, name) VALUES (748, 'Progress Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (749, 'Project Co-ordinator');
INSERT INTO "public"."skills" (id, name) VALUES (750, 'Project Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (751, 'Project Leader');
INSERT INTO "public"."skills" (id, name) VALUES (752, 'Project Manager');
INSERT INTO "public"."skills" (id, name) VALUES (753, 'Project Worker');
INSERT INTO "public"."skills" (id, name) VALUES (754, 'Projectionist');
INSERT INTO "public"."skills" (id, name) VALUES (755, 'Promoter');
INSERT INTO "public"."skills" (id, name) VALUES (756, 'Proof Reader');
INSERT INTO "public"."skills" (id, name) VALUES (757, 'Property Buyer');
INSERT INTO "public"."skills" (id, name) VALUES (758, 'Property Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (759, 'Property Developer');
INSERT INTO "public"."skills" (id, name) VALUES (760, 'Property Manager');
INSERT INTO "public"."skills" (id, name) VALUES (761, 'Property Valuer');
INSERT INTO "public"."skills" (id, name) VALUES (762, 'Proprietor');
INSERT INTO "public"."skills" (id, name) VALUES (763, 'Psychiatrist');
INSERT INTO "public"."skills" (id, name) VALUES (764, 'Psychoanalyst');
INSERT INTO "public"."skills" (id, name) VALUES (765, 'Psychologist');
INSERT INTO "public"."skills" (id, name) VALUES (766, 'Psychotherapist');
INSERT INTO "public"."skills" (id, name) VALUES (767, 'Public House Manager');
INSERT INTO "public"."skills" (id, name) VALUES (768, 'Public Relations Of?cer');
INSERT INTO "public"."skills" (id, name) VALUES (769, 'Publican');
INSERT INTO "public"."skills" (id, name) VALUES (770, 'Publicity Manager');
INSERT INTO "public"."skills" (id, name) VALUES (771, 'Publisher');
INSERT INTO "public"."skills" (id, name) VALUES (772, 'Publishing Manager');
INSERT INTO "public"."skills" (id, name) VALUES (773, 'Purchase Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (774, 'Purchase Ledger Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (775, 'Purchasing Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (776, 'Purchasing Manager');
INSERT INTO "public"."skills" (id, name) VALUES (777, 'Purser');
INSERT INTO "public"."skills" (id, name) VALUES (778, 'Quality Controller');
INSERT INTO "public"."skills" (id, name) VALUES (779, 'Quality Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (780, 'Quality Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (781, 'Quality Manager');
INSERT INTO "public"."skills" (id, name) VALUES (782, 'Quality Technician');
INSERT INTO "public"."skills" (id, name) VALUES (783, 'Quantity Surveyor');
INSERT INTO "public"."skills" (id, name) VALUES (784, 'Quarry Worker');
INSERT INTO "public"."skills" (id, name) VALUES (785, 'Racehorse Groom');
INSERT INTO "public"."skills" (id, name) VALUES (786, 'Racing Organiser');
INSERT INTO "public"."skills" (id, name) VALUES (787, 'Radio Controller');
INSERT INTO "public"."skills" (id, name) VALUES (788, 'Radio Director');
INSERT INTO "public"."skills" (id, name) VALUES (789, 'Radio Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (790, 'Radio Operator');
INSERT INTO "public"."skills" (id, name) VALUES (791, 'Radio Presenter');
INSERT INTO "public"."skills" (id, name) VALUES (792, 'Radio Producer');
INSERT INTO "public"."skills" (id, name) VALUES (793, 'Radiographer');
INSERT INTO "public"."skills" (id, name) VALUES (794, 'Radiologist');
INSERT INTO "public"."skills" (id, name) VALUES (795, 'Rally Driver');
INSERT INTO "public"."skills" (id, name) VALUES (796, 'Receptionist');
INSERT INTO "public"."skills" (id, name) VALUES (797, 'Recorder');
INSERT INTO "public"."skills" (id, name) VALUES (798, 'Records Supervisor');
INSERT INTO "public"."skills" (id, name) VALUES (799, 'Recovery Vehicle Coordinator');
INSERT INTO "public"."skills" (id, name) VALUES (800, 'Recreational');
INSERT INTO "public"."skills" (id, name) VALUES (801, 'Recruitment Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (802, 'Rector');
INSERT INTO "public"."skills" (id, name) VALUES (803, 'Reflexologist');
INSERT INTO "public"."skills" (id, name) VALUES (804, 'Refractory Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (805, 'Refrigeration Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (806, 'Refuse Collector');
INSERT INTO "public"."skills" (id, name) VALUES (807, 'Registrar');
INSERT INTO "public"."skills" (id, name) VALUES (808, 'Regulator');
INSERT INTO "public"."skills" (id, name) VALUES (809, 'Relocation Agent');
INSERT INTO "public"."skills" (id, name) VALUES (810, 'Remedial Therapist');
INSERT INTO "public"."skills" (id, name) VALUES (811, 'Rent Collector');
INSERT INTO "public"."skills" (id, name) VALUES (812, 'Rent Offcer');
INSERT INTO "public"."skills" (id, name) VALUES (813, 'Repair Man');
INSERT INTO "public"."skills" (id, name) VALUES (814, 'Repairer');
INSERT INTO "public"."skills" (id, name) VALUES (815, 'Reporter');
INSERT INTO "public"."skills" (id, name) VALUES (816, 'Representative');
INSERT INTO "public"."skills" (id, name) VALUES (817, 'Reprographic Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (818, 'Research Analyst');
INSERT INTO "public"."skills" (id, name) VALUES (819, 'Research Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (820, 'Research Director');
INSERT INTO "public"."skills" (id, name) VALUES (821, 'Research Scientist');
INSERT INTO "public"."skills" (id, name) VALUES (822, 'Research Technician');
INSERT INTO "public"."skills" (id, name) VALUES (823, 'Researcher');
INSERT INTO "public"."skills" (id, name) VALUES (824, 'Resin Caster');
INSERT INTO "public"."skills" (id, name) VALUES (825, 'Restaurant Manager');
INSERT INTO "public"."skills" (id, name) VALUES (826, 'Restaurateur');
INSERT INTO "public"."skills" (id, name) VALUES (827, 'Restorer');
INSERT INTO "public"."skills" (id, name) VALUES (828, 'Retired');
INSERT INTO "public"."skills" (id, name) VALUES (829, 'Revenue Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (830, 'Revenue Officer');
INSERT INTO "public"."skills" (id, name) VALUES (831, 'Riding Instructor');
INSERT INTO "public"."skills" (id, name) VALUES (832, 'Rig Worker');
INSERT INTO "public"."skills" (id, name) VALUES (833, 'Rigger');
INSERT INTO "public"."skills" (id, name) VALUES (834, 'Riveter');
INSERT INTO "public"."skills" (id, name) VALUES (835, 'Road Safety Officer');
INSERT INTO "public"."skills" (id, name) VALUES (836, 'Road Sweeper');
INSERT INTO "public"."skills" (id, name) VALUES (837, 'Road Worker');
INSERT INTO "public"."skills" (id, name) VALUES (838, 'Roadworker');
INSERT INTO "public"."skills" (id, name) VALUES (839, 'Roof Tiler');
INSERT INTO "public"."skills" (id, name) VALUES (840, 'Roofer');
INSERT INTO "public"."skills" (id, name) VALUES (841, 'Rose Grower');
INSERT INTO "public"."skills" (id, name) VALUES (842, 'Royal Marine');
INSERT INTO "public"."skills" (id, name) VALUES (843, 'Rug Maker');
INSERT INTO "public"."skills" (id, name) VALUES (844, 'Saddler');
INSERT INTO "public"."skills" (id, name) VALUES (845, 'Safety Officer');
INSERT INTO "public"."skills" (id, name) VALUES (846, 'Sail Maker');
INSERT INTO "public"."skills" (id, name) VALUES (847, 'Sales Administrator');
INSERT INTO "public"."skills" (id, name) VALUES (848, 'Sales Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (849, 'Sales Director');
INSERT INTO "public"."skills" (id, name) VALUES (850, 'Sales Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (851, 'Sales Executive');
INSERT INTO "public"."skills" (id, name) VALUES (852, 'Sales Manager');
INSERT INTO "public"."skills" (id, name) VALUES (853, 'Sales Representative');
INSERT INTO "public"."skills" (id, name) VALUES (854, 'Sales Support');
INSERT INTO "public"."skills" (id, name) VALUES (855, 'Salesman');
INSERT INTO "public"."skills" (id, name) VALUES (856, 'Saleswoman');
INSERT INTO "public"."skills" (id, name) VALUES (857, 'Sand Blaster');
INSERT INTO "public"."skills" (id, name) VALUES (858, 'Saw Miller');
INSERT INTO "public"."skills" (id, name) VALUES (859, 'Scaffolder');
INSERT INTO "public"."skills" (id, name) VALUES (860, 'School Crossing');
INSERT INTO "public"."skills" (id, name) VALUES (861, 'School Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (862, 'Scientific Officer');
INSERT INTO "public"."skills" (id, name) VALUES (863, 'Scientist');
INSERT INTO "public"."skills" (id, name) VALUES (864, 'Scrap Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (865, 'Screen Printer');
INSERT INTO "public"."skills" (id, name) VALUES (866, 'Screen Writer');
INSERT INTO "public"."skills" (id, name) VALUES (867, 'Script Writer');
INSERT INTO "public"."skills" (id, name) VALUES (868, 'Sculptor');
INSERT INTO "public"."skills" (id, name) VALUES (869, 'Seaman');
INSERT INTO "public"."skills" (id, name) VALUES (870, 'Seamstress');
INSERT INTO "public"."skills" (id, name) VALUES (871, 'Secretary');
INSERT INTO "public"."skills" (id, name) VALUES (872, 'Security Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (873, 'Security Controller');
INSERT INTO "public"."skills" (id, name) VALUES (874, 'Security Guard');
INSERT INTO "public"."skills" (id, name) VALUES (875, 'Security Officer');
INSERT INTO "public"."skills" (id, name) VALUES (876, 'Servant');
INSERT INTO "public"."skills" (id, name) VALUES (877, 'Service Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (878, 'Service Manager');
INSERT INTO "public"."skills" (id, name) VALUES (879, 'Share Dealer');
INSERT INTO "public"."skills" (id, name) VALUES (880, 'Sheet Metal Worker');
INSERT INTO "public"."skills" (id, name) VALUES (881, 'Shelf Filler');
INSERT INTO "public"."skills" (id, name) VALUES (882, 'Shelter Warden');
INSERT INTO "public"."skills" (id, name) VALUES (883, 'Shepherd');
INSERT INTO "public"."skills" (id, name) VALUES (884, 'Sheriff');
INSERT INTO "public"."skills" (id, name) VALUES (885, 'Sheriff Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (886, 'Sheriff Principal');
INSERT INTO "public"."skills" (id, name) VALUES (887, 'Shift Controller');
INSERT INTO "public"."skills" (id, name) VALUES (888, 'Ship Broker');
INSERT INTO "public"."skills" (id, name) VALUES (889, 'Ship Builder');
INSERT INTO "public"."skills" (id, name) VALUES (890, 'Shipping Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (891, 'Shipping Officer');
INSERT INTO "public"."skills" (id, name) VALUES (892, 'Shipwright');
INSERT INTO "public"."skills" (id, name) VALUES (893, 'Shipyard Worker');
INSERT INTO "public"."skills" (id, name) VALUES (894, 'Shoe Maker');
INSERT INTO "public"."skills" (id, name) VALUES (895, 'Shoe Repairer');
INSERT INTO "public"."skills" (id, name) VALUES (896, 'Shooting Instructor');
INSERT INTO "public"."skills" (id, name) VALUES (897, 'Shop Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (898, 'Shop Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (899, 'Shop Keeper');
INSERT INTO "public"."skills" (id, name) VALUES (900, 'Shop Manager');
INSERT INTO "public"."skills" (id, name) VALUES (901, 'Shop Proprietor');
INSERT INTO "public"."skills" (id, name) VALUES (902, 'Shot Blaster');
INSERT INTO "public"."skills" (id, name) VALUES (903, 'Show Jumper');
INSERT INTO "public"."skills" (id, name) VALUES (904, 'Showman');
INSERT INTO "public"."skills" (id, name) VALUES (905, 'Shunter');
INSERT INTO "public"."skills" (id, name) VALUES (906, 'Sign Maker');
INSERT INTO "public"."skills" (id, name) VALUES (907, 'Signalman');
INSERT INTO "public"."skills" (id, name) VALUES (908, 'Signwriter');
INSERT INTO "public"."skills" (id, name) VALUES (909, 'Site Agent');
INSERT INTO "public"."skills" (id, name) VALUES (910, 'Site Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (911, 'Skipper');
INSERT INTO "public"."skills" (id, name) VALUES (912, 'Slater');
INSERT INTO "public"."skills" (id, name) VALUES (913, 'Slaughterman');
INSERT INTO "public"."skills" (id, name) VALUES (914, 'Smallholder');
INSERT INTO "public"."skills" (id, name) VALUES (915, 'Social Worker');
INSERT INTO "public"."skills" (id, name) VALUES (916, 'Software Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (917, 'Software Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (918, 'Soldier');
INSERT INTO "public"."skills" (id, name) VALUES (919, 'Solicitor');
INSERT INTO "public"."skills" (id, name) VALUES (920, 'Song Writer');
INSERT INTO "public"."skills" (id, name) VALUES (921, 'Sound Artist');
INSERT INTO "public"."skills" (id, name) VALUES (922, 'Sound Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (923, 'Sound Technician');
INSERT INTO "public"."skills" (id, name) VALUES (924, 'Special Constable');
INSERT INTO "public"."skills" (id, name) VALUES (925, 'Special Needs');
INSERT INTO "public"."skills" (id, name) VALUES (926, 'Speech Therapist');
INSERT INTO "public"."skills" (id, name) VALUES (927, 'Sports Administrator');
INSERT INTO "public"."skills" (id, name) VALUES (928, 'Sports Coach');
INSERT INTO "public"."skills" (id, name) VALUES (929, 'Sports Commentator');
INSERT INTO "public"."skills" (id, name) VALUES (930, 'Sportsman');
INSERT INTO "public"."skills" (id, name) VALUES (931, 'Sportsperson');
INSERT INTO "public"."skills" (id, name) VALUES (932, 'Sportswoman');
INSERT INTO "public"."skills" (id, name) VALUES (933, 'Spring Maker');
INSERT INTO "public"."skills" (id, name) VALUES (934, 'Stable Hand');
INSERT INTO "public"."skills" (id, name) VALUES (935, 'Staff Nurse');
INSERT INTO "public"."skills" (id, name) VALUES (936, 'Stage Director');
INSERT INTO "public"."skills" (id, name) VALUES (937, 'Stage Hand');
INSERT INTO "public"."skills" (id, name) VALUES (938, 'Stage Manager');
INSERT INTO "public"."skills" (id, name) VALUES (939, 'Stage Mover');
INSERT INTO "public"."skills" (id, name) VALUES (940, 'Station Manager');
INSERT INTO "public"."skills" (id, name) VALUES (941, 'Stationer');
INSERT INTO "public"."skills" (id, name) VALUES (942, 'Statistician');
INSERT INTO "public"."skills" (id, name) VALUES (943, 'Steel Erector');
INSERT INTO "public"."skills" (id, name) VALUES (944, 'Steel Worker');
INSERT INTO "public"."skills" (id, name) VALUES (945, 'Steeplejack');
INSERT INTO "public"."skills" (id, name) VALUES (946, 'Stenographer');
INSERT INTO "public"."skills" (id, name) VALUES (947, 'Steward');
INSERT INTO "public"."skills" (id, name) VALUES (948, 'Stewardess');
INSERT INTO "public"."skills" (id, name) VALUES (949, 'Stock Controller');
INSERT INTO "public"."skills" (id, name) VALUES (950, 'Stock Manager');
INSERT INTO "public"."skills" (id, name) VALUES (951, 'Stockbroker');
INSERT INTO "public"."skills" (id, name) VALUES (952, 'Stockman');
INSERT INTO "public"."skills" (id, name) VALUES (953, 'Stocktaker');
INSERT INTO "public"."skills" (id, name) VALUES (954, 'Stone Cutter');
INSERT INTO "public"."skills" (id, name) VALUES (955, 'Stone Sawyer');
INSERT INTO "public"."skills" (id, name) VALUES (956, 'Stonemason');
INSERT INTO "public"."skills" (id, name) VALUES (957, 'Store Detective');
INSERT INTO "public"."skills" (id, name) VALUES (958, 'Storeman');
INSERT INTO "public"."skills" (id, name) VALUES (959, 'Storewoman');
INSERT INTO "public"."skills" (id, name) VALUES (960, 'Street Entertainer');
INSERT INTO "public"."skills" (id, name) VALUES (961, 'Street Trader');
INSERT INTO "public"."skills" (id, name) VALUES (962, 'Stud Hand');
INSERT INTO "public"."skills" (id, name) VALUES (963, 'Student');
INSERT INTO "public"."skills" (id, name) VALUES (964, 'Student Nurse');
INSERT INTO "public"."skills" (id, name) VALUES (965, 'Student Teacher');
INSERT INTO "public"."skills" (id, name) VALUES (966, 'Studio Manager');
INSERT INTO "public"."skills" (id, name) VALUES (967, 'Sub-Postmaster');
INSERT INTO "public"."skills" (id, name) VALUES (968, 'Sub-Postmistress');
INSERT INTO "public"."skills" (id, name) VALUES (969, 'Supervisor');
INSERT INTO "public"."skills" (id, name) VALUES (970, 'Supply Teacher');
INSERT INTO "public"."skills" (id, name) VALUES (971, 'Surgeon');
INSERT INTO "public"."skills" (id, name) VALUES (972, 'Surveyor');
INSERT INTO "public"."skills" (id, name) VALUES (973, 'Systems Analyst');
INSERT INTO "public"."skills" (id, name) VALUES (974, 'Systems Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (975, 'Systems Manager');
INSERT INTO "public"."skills" (id, name) VALUES (976, 'TV Editor');
INSERT INTO "public"."skills" (id, name) VALUES (977, 'Tachograph Analyst');
INSERT INTO "public"."skills" (id, name) VALUES (978, 'Tacker');
INSERT INTO "public"."skills" (id, name) VALUES (979, 'Tailor');
INSERT INTO "public"."skills" (id, name) VALUES (980, 'Tank Farm Operative');
INSERT INTO "public"."skills" (id, name) VALUES (981, 'Tanker Driver');
INSERT INTO "public"."skills" (id, name) VALUES (982, 'Tanner');
INSERT INTO "public"."skills" (id, name) VALUES (983, 'Tattooist');
INSERT INTO "public"."skills" (id, name) VALUES (984, 'Tax Advisor');
INSERT INTO "public"."skills" (id, name) VALUES (985, 'Tax Analyst');
INSERT INTO "public"."skills" (id, name) VALUES (986, 'Tax Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (987, 'Tax Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (988, 'Tax Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (989, 'Tax Manager');
INSERT INTO "public"."skills" (id, name) VALUES (990, 'Tax Officer');
INSERT INTO "public"."skills" (id, name) VALUES (991, 'Taxi Controller');
INSERT INTO "public"."skills" (id, name) VALUES (992, 'Taxi Driver');
INSERT INTO "public"."skills" (id, name) VALUES (993, 'Taxidermist');
INSERT INTO "public"."skills" (id, name) VALUES (994, 'Tea Blender');
INSERT INTO "public"."skills" (id, name) VALUES (995, 'Tea Taster');
INSERT INTO "public"."skills" (id, name) VALUES (996, 'Teacher');
INSERT INTO "public"."skills" (id, name) VALUES (997, 'Teachers Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (998, 'Technical Advisor');
INSERT INTO "public"."skills" (id, name) VALUES (999, 'Technical Analyst');
INSERT INTO "public"."skills" (id, name) VALUES (1000, 'Technical Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (1001, 'Technical Author');
INSERT INTO "public"."skills" (id, name) VALUES (1002, 'Technical Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (1003, 'Technical Co-ordinator');
INSERT INTO "public"."skills" (id, name) VALUES (1004, 'Technical Director');
INSERT INTO "public"."skills" (id, name) VALUES (1005, 'Technical Editor');
INSERT INTO "public"."skills" (id, name) VALUES (1006, 'Technical Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (1007, 'Technical Illustrator');
INSERT INTO "public"."skills" (id, name) VALUES (1008, 'Technical Instructor');
INSERT INTO "public"."skills" (id, name) VALUES (1009, 'Technical Liaison');
INSERT INTO "public"."skills" (id, name) VALUES (1010, 'Technical Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1011, 'Technician');
INSERT INTO "public"."skills" (id, name) VALUES (1012, 'Telecommunication');
INSERT INTO "public"."skills" (id, name) VALUES (1013, 'Telecommunications');
INSERT INTO "public"."skills" (id, name) VALUES (1014, 'Telegraphist');
INSERT INTO "public"."skills" (id, name) VALUES (1015, 'Telemarketeer');
INSERT INTO "public"."skills" (id, name) VALUES (1016, 'Telephone Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (1017, 'Telephonist');
INSERT INTO "public"."skills" (id, name) VALUES (1018, 'Telesales Person');
INSERT INTO "public"."skills" (id, name) VALUES (1019, 'Television Director');
INSERT INTO "public"."skills" (id, name) VALUES (1020, 'Television Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (1021, 'Television Presenter');
INSERT INTO "public"."skills" (id, name) VALUES (1022, 'Television Producer');
INSERT INTO "public"."skills" (id, name) VALUES (1023, 'Telex Operator');
INSERT INTO "public"."skills" (id, name) VALUES (1024, 'Temperature Time');
INSERT INTO "public"."skills" (id, name) VALUES (1025, 'Tennis Coach');
INSERT INTO "public"."skills" (id, name) VALUES (1026, 'Textile Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (1027, 'Textile Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (1028, 'Textile Technician');
INSERT INTO "public"."skills" (id, name) VALUES (1029, 'Textile Worker');
INSERT INTO "public"."skills" (id, name) VALUES (1030, 'Thatcher');
INSERT INTO "public"."skills" (id, name) VALUES (1031, 'Theatre Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1032, 'Theatre Technician');
INSERT INTO "public"."skills" (id, name) VALUES (1033, 'Theatrical Agent');
INSERT INTO "public"."skills" (id, name) VALUES (1034, 'Therapist');
INSERT INTO "public"."skills" (id, name) VALUES (1035, 'Thermal Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (1036, 'Thermal Insulator');
INSERT INTO "public"."skills" (id, name) VALUES (1037, 'Ticket Agent');
INSERT INTO "public"."skills" (id, name) VALUES (1038, 'Ticket Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (1039, 'Tiler');
INSERT INTO "public"."skills" (id, name) VALUES (1040, 'Timber Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (1041, 'Timber Worker');
INSERT INTO "public"."skills" (id, name) VALUES (1042, 'Tobacconist');
INSERT INTO "public"."skills" (id, name) VALUES (1043, 'Toll Collector');
INSERT INTO "public"."skills" (id, name) VALUES (1044, 'Tool Maker');
INSERT INTO "public"."skills" (id, name) VALUES (1045, 'Tour Agent');
INSERT INTO "public"."skills" (id, name) VALUES (1046, 'Tour Guide');
INSERT INTO "public"."skills" (id, name) VALUES (1047, 'Town Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (1048, 'Town Planner');
INSERT INTO "public"."skills" (id, name) VALUES (1049, 'Toy Maker');
INSERT INTO "public"."skills" (id, name) VALUES (1050, 'Toy Trader');
INSERT INTO "public"."skills" (id, name) VALUES (1051, 'Track Worker');
INSERT INTO "public"."skills" (id, name) VALUES (1052, 'Tractor Driver');
INSERT INTO "public"."skills" (id, name) VALUES (1053, 'Tractor Mechanic');
INSERT INTO "public"."skills" (id, name) VALUES (1054, 'Trade Mark Agent');
INSERT INTO "public"."skills" (id, name) VALUES (1055, 'Trade Union Official');
INSERT INTO "public"."skills" (id, name) VALUES (1056, 'Trading Standards');
INSERT INTO "public"."skills" (id, name) VALUES (1057, 'Traffic Warden');
INSERT INTO "public"."skills" (id, name) VALUES (1058, 'Train Driver');
INSERT INTO "public"."skills" (id, name) VALUES (1059, 'Trainee Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1060, 'Training Advisor');
INSERT INTO "public"."skills" (id, name) VALUES (1061, 'Training Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (1062, 'Training Co-ordinator');
INSERT INTO "public"."skills" (id, name) VALUES (1063, 'Training Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (1064, 'Training Instructor');
INSERT INTO "public"."skills" (id, name) VALUES (1065, 'Training Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1066, 'Training Officer');
INSERT INTO "public"."skills" (id, name) VALUES (1067, 'Transcriber');
INSERT INTO "public"."skills" (id, name) VALUES (1068, 'Translator');
INSERT INTO "public"."skills" (id, name) VALUES (1069, 'Transport Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (1070, 'Transport Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (1071, 'Transport Controller');
INSERT INTO "public"."skills" (id, name) VALUES (1072, 'Transport Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (1073, 'Transport Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1074, 'Transport Officer');
INSERT INTO "public"."skills" (id, name) VALUES (1075, 'Transport Planner');
INSERT INTO "public"."skills" (id, name) VALUES (1076, 'Travel Agent');
INSERT INTO "public"."skills" (id, name) VALUES (1077, 'Travel Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (1078, 'Travel Consultant');
INSERT INTO "public"."skills" (id, name) VALUES (1079, 'Travel Courier');
INSERT INTO "public"."skills" (id, name) VALUES (1080, 'Travel Guide');
INSERT INTO "public"."skills" (id, name) VALUES (1081, 'Travel Guide Writer');
INSERT INTO "public"."skills" (id, name) VALUES (1082, 'Travel Representative');
INSERT INTO "public"."skills" (id, name) VALUES (1083, 'Travelling Showman');
INSERT INTO "public"."skills" (id, name) VALUES (1084, 'Treasurer');
INSERT INTO "public"."skills" (id, name) VALUES (1085, 'Tree Feller');
INSERT INTO "public"."skills" (id, name) VALUES (1086, 'Tree Surgeon');
INSERT INTO "public"."skills" (id, name) VALUES (1087, 'Trichologist');
INSERT INTO "public"."skills" (id, name) VALUES (1088, 'Trinity House Pilot');
INSERT INTO "public"."skills" (id, name) VALUES (1089, 'Trout Farmer');
INSERT INTO "public"."skills" (id, name) VALUES (1090, 'Tug Skipper');
INSERT INTO "public"."skills" (id, name) VALUES (1091, 'Tunneller');
INSERT INTO "public"."skills" (id, name) VALUES (1092, 'Turf Accountant');
INSERT INTO "public"."skills" (id, name) VALUES (1093, 'Turkey Farmer');
INSERT INTO "public"."skills" (id, name) VALUES (1094, 'Turner');
INSERT INTO "public"."skills" (id, name) VALUES (1095, 'Tutor');
INSERT INTO "public"."skills" (id, name) VALUES (1096, 'Typesetter');
INSERT INTO "public"."skills" (id, name) VALUES (1097, 'Typewriter Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (1098, 'Typist');
INSERT INTO "public"."skills" (id, name) VALUES (1099, 'Tyre Builder');
INSERT INTO "public"."skills" (id, name) VALUES (1100, 'Tyre Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (1101, 'Tyre Inspector');
INSERT INTO "public"."skills" (id, name) VALUES (1102, 'Tyre Technician');
INSERT INTO "public"."skills" (id, name) VALUES (1103, 'Undertaker');
INSERT INTO "public"."skills" (id, name) VALUES (1104, 'Underwriter');
INSERT INTO "public"."skills" (id, name) VALUES (1105, 'Upholsterer');
INSERT INTO "public"."skills" (id, name) VALUES (1106, 'Valuer');
INSERT INTO "public"."skills" (id, name) VALUES (1107, 'Valve Technician');
INSERT INTO "public"."skills" (id, name) VALUES (1108, 'Van Driver');
INSERT INTO "public"."skills" (id, name) VALUES (1109, 'Vehicle Assessor');
INSERT INTO "public"."skills" (id, name) VALUES (1110, 'Vehicle Body Worker');
INSERT INTO "public"."skills" (id, name) VALUES (1111, 'Vehicle Engineer');
INSERT INTO "public"."skills" (id, name) VALUES (1112, 'Vehicle Technician');
INSERT INTO "public"."skills" (id, name) VALUES (1113, 'Ventriloquist');
INSERT INTO "public"."skills" (id, name) VALUES (1114, 'Verger');
INSERT INTO "public"."skills" (id, name) VALUES (1115, 'Veterinary Surgeon');
INSERT INTO "public"."skills" (id, name) VALUES (1116, 'Vicar');
INSERT INTO "public"."skills" (id, name) VALUES (1117, 'Video Artist');
INSERT INTO "public"."skills" (id, name) VALUES (1118, 'Violin Maker');
INSERT INTO "public"."skills" (id, name) VALUES (1119, 'Violinist');
INSERT INTO "public"."skills" (id, name) VALUES (1120, 'Voluntary Worker');
INSERT INTO "public"."skills" (id, name) VALUES (1121, 'Wages Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (1122, 'Waiter');
INSERT INTO "public"."skills" (id, name) VALUES (1123, 'Waitress');
INSERT INTO "public"."skills" (id, name) VALUES (1124, 'Warden');
INSERT INTO "public"."skills" (id, name) VALUES (1125, 'Warehouse Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1126, 'Warehouseman');
INSERT INTO "public"."skills" (id, name) VALUES (1127, 'Warehousewoman');
INSERT INTO "public"."skills" (id, name) VALUES (1128, 'Watchmaker');
INSERT INTO "public"."skills" (id, name) VALUES (1129, 'Weaver');
INSERT INTO "public"."skills" (id, name) VALUES (1130, 'Weighbridge Clerk');
INSERT INTO "public"."skills" (id, name) VALUES (1131, 'Weighbridge Operator');
INSERT INTO "public"."skills" (id, name) VALUES (1132, 'Welder');
INSERT INTO "public"."skills" (id, name) VALUES (1133, 'Welfare Assistant');
INSERT INTO "public"."skills" (id, name) VALUES (1134, 'Welfare Officer');
INSERT INTO "public"."skills" (id, name) VALUES (1135, 'Welfare Rights Officer');
INSERT INTO "public"."skills" (id, name) VALUES (1136, 'Wheel Clamper');
INSERT INTO "public"."skills" (id, name) VALUES (1137, 'Wholesale Newspaper');
INSERT INTO "public"."skills" (id, name) VALUES (1138, 'Window Cleaner');
INSERT INTO "public"."skills" (id, name) VALUES (1139, 'Window Dresser');
INSERT INTO "public"."skills" (id, name) VALUES (1140, 'Windscreen Fitter');
INSERT INTO "public"."skills" (id, name) VALUES (1141, 'Wine Merchant');
INSERT INTO "public"."skills" (id, name) VALUES (1142, 'Wood Carver');
INSERT INTO "public"."skills" (id, name) VALUES (1143, 'Wood Cutter');
INSERT INTO "public"."skills" (id, name) VALUES (1144, 'Wood Worker');
INSERT INTO "public"."skills" (id, name) VALUES (1145, 'Word Processing Operator');
INSERT INTO "public"."skills" (id, name) VALUES (1146, 'Works Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1147, 'Writer');
INSERT INTO "public"."skills" (id, name) VALUES (1148, 'Yacht Master');
INSERT INTO "public"."skills" (id, name) VALUES (1149, 'Yard Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1150, 'Youth Hostel Warden');
INSERT INTO "public"."skills" (id, name) VALUES (1151, 'Youth Worker');
INSERT INTO "public"."skills" (id, name) VALUES (1152, 'Zoo Keeper');
INSERT INTO "public"."skills" (id, name) VALUES (1153, 'Zoo Manager');
INSERT INTO "public"."skills" (id, name) VALUES (1154, 'Zoologist');
INSERT INTO "public"."skills" (id, name) VALUES (1155,  "Advertising Services");
INSERT INTO "public"."skills" (id, name) VALUES (1156,  "Business Consulting and Services");
INSERT INTO "public"."skills" (id, name) VALUES (1157,  "Civic and Social Organizations");
INSERT INTO "public"."skills" (id, name) VALUES (1158,  "Computer Games");
INSERT INTO "public"."skills" (id, name) VALUES (1159,  "Computer and Network Security");
INSERT INTO "public"."skills" (id, name) VALUES (1160,  "Education Administration Programs");
INSERT INTO "public"."skills" (id, name) VALUES (1161,  "Financial Services");
INSERT INTO "public"."skills" (id, name) VALUES (1162,  "Human Resources Services");
INSERT INTO "public"."skills" (id, name) VALUES (1163,  "IT Services & Solutions Company");
INSERT INTO "public"."skills" (id, name) VALUES (1164,  "IT Services and IT Consulting");
INSERT INTO "public"."skills" (id, name) VALUES (1165,  "Individual and Family Services");
INSERT INTO "public"."skills" (id, name) VALUES (1166,  "Industrial Machinery Manufacturing");
INSERT INTO "public"."skills" (id, name) VALUES (1167,  "Information Technology & Services");
INSERT INTO "public"."skills" (id, name) VALUES (1168,  "Information and Internet");
INSERT INTO "public"."skills" (id, name) VALUES (1169,  "Insurance");
INSERT INTO "public"."skills" (id, name) VALUES (1170,  "Marketing Services");
INSERT INTO "public"."skills" (id, name) VALUES (1171,  "Outsourcing and Offshoring Consulting");
INSERT INTO "public"."skills" (id, name) VALUES (1172,  "Retail");
INSERT INTO "public"."skills" (id, name) VALUES (1173,  "Software Development");
INSERT INTO "public"."skills" (id, name) VALUES (1174,  "Spectator Sports");
INSERT INTO "public"."skills" (id, name) VALUES (1175,  "Staffing and Recruiting");
INSERT INTO "public"."skills" (id, name) VALUES (1176,  "Technology");
INSERT INTO "public"."skills" (id, name) VALUES (1177,  "Technology, Information and Internet");

