INSERT INTO "public"."skills" (name)
VALUES ('Communication Skills'),
       ('Leadership Skills'),
       ('Problem Solving'),
       ('Critical Thinking'),
       ('Time Management'),
       ('Adaptability'),
       ('Teamwork'),
       ('Creativity'),
       ('Analytical Skills'),
       ('Decision Making'),
       ('Attention to Detail'),
       ('Organizational Skills'),
       ('Project Management'),
       ('Presentation Skills'),
       ('Research Skills'),
       ('Negotiation Skills'),
       ('Collaboration'),
       ('Customer Service'),
       ('Sales Skills'),
       ('Marketing Skills'),
       ('Financial Management'),
       ('Business Development'),
       ('Strategic Planning'),
       ('Data Analysis'),
       ('Statistical Analysis'),
       ('Reporting and Documentation'),
       ('Technical Writing'),
       ('Troubleshooting'),
       ('Training and Development'),
       ('Change Management'),
       ('Risk Management'),
       ('Salesforce CRM'),
       ('Microsoft Office Suite'),
       ('Google Suite'),
       ('Social Media Management'),
       ('Content Creation'),
       ('Public Speaking'),
       ('Graphic Design'),
       ('Video Editing'),
       ('SEO (Search Engine Optimization)'),
       ('Copywriting'),
       ('Market Research'),
       ('UX/UI Design'),
       ('Mobile App Design'),
       ('Event Planning'),
       ('Budgeting and Forecasting'),
       ('Contract Management'),
       ('Supply Chain Management'),
       ('Vendor Management');
